"""Utility functions used by DHPCTIndividual

Docs: https://perceptualrobots.github.io/dpctindividual_utils.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_individual_utils.ipynb.

# %% auto #0
__all__ = ['calculate_rms_error', 'calculate_mae_error', 'ExecutionHistory', 'config_to_legacy_config']

# %% ../nbs/02_individual_utils.ipynb #757d0df7
import numpy as np
import json
import pickle
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional, Dict, List, Any

# %% ../nbs/02_individual_utils.ipynb #047aa210
def calculate_rms_error(errors: np.ndarray) -> float:
    """Calculate Root Mean Square (RMS) error."""
    return np.sqrt(np.mean(errors ** 2))


def calculate_mae_error(errors: np.ndarray) -> float:
    """Calculate Mean Absolute Error (MAE)."""
    return np.mean(np.abs(errors))


def _to_serializable(value):
    if isinstance(value, np.ndarray):
        return value.tolist()
    if isinstance(value, (np.floating, np.integer)):
        return value.item()
    if isinstance(value, dict):
        return {k: _to_serializable(v) for k, v in value.items()}
    if isinstance(value, (list, tuple)):
        return [_to_serializable(v) for v in value]
    if isinstance(value, set):
        return sorted(list(value))
    return value


def _to_numpy(value):
    if isinstance(value, (list, tuple)):
        return np.array(value, dtype=np.float32)
    if isinstance(value, (int, float, np.integer, np.floating)):
        return np.array(value, dtype=np.float32)
    return value


# %% ../nbs/02_individual_utils.ipynb #388199b8
import time as _time


class ExecutionHistory:
    """Record of all state transitions during an individual's execution in an environment.
    
    Stores observations, actions, rewards, errors, layer activations, termination
    flags, and timestamps for each step of an execution episode.
    """
    
    def __init__(self):
        # ``observations`` keeps the post-step observation returned by env.step()
        # for backward compatibility with existing metrics/processors.  The
        # optional ``pre_observations`` trace records the observation that the
        # controller actually perceived before taking each action, allowing
        # plots and verbose output to show the full transition.
        self.observations: List[np.ndarray] = []
        self.pre_observations: List[np.ndarray] = []
        self.actions: List[Any] = []
        self.rewards: List[float] = []
        self.errors: List[np.ndarray] = []
        self.layer_activations: Dict[str, List[np.ndarray]] = {}
        self.terminated: List[bool] = []
        self.truncated: List[bool] = []
        self.timestamps: List[float] = []
        self._start_time: Optional[float] = None
    
    def add_step(
        self,
        observation: np.ndarray,
        action: Any,
        reward: float,
        error: np.ndarray,
        done: bool = False,
        terminated: bool = False,
        truncated: bool = False,
        layer_activations: Optional[Dict[str, np.ndarray]] = None,
        pre_observation: Optional[np.ndarray] = None,
    ):
        """Record a single execution step.
        
        Args:
            observation: Environment observation returned after the action
            action: Action taken at this step
            reward: Reward received
            error: Comparator error values at this step
            done: Legacy flag (sets terminated=True if neither terminated/truncated given)
            terminated: Whether episode terminated at this step
            truncated: Whether episode was truncated at this step
            layer_activations: Optional dict mapping layer names to activation arrays
            pre_observation: Observation used to compute the action. If omitted,
                defaults to ``observation`` for compatibility with older callers.
        """
        if self._start_time is None:
            self._start_time = _time.time()
        
        self.observations.append(np.array(observation, dtype=np.float32))
        if pre_observation is None:
            pre_observation = observation
        self.pre_observations.append(np.array(pre_observation, dtype=np.float32))
        self.actions.append(action)
        self.rewards.append(float(reward))
        self.errors.append(np.array(error, dtype=np.float32))
        
        # Handle termination flags
        if not terminated and not truncated and done:
            terminated = True
        self.terminated.append(terminated)
        self.truncated.append(truncated)
        
        self.timestamps.append(_time.time() - self._start_time)
        
        if layer_activations is not None:
            for name, values in layer_activations.items():
                if name not in self.layer_activations:
                    self.layer_activations[name] = []
                self.layer_activations[name].append(np.array(values, dtype=np.float32))
    
    def __len__(self) -> int:
        return len(self.observations)
    
    @property
    def num_steps(self) -> int:
        """Number of recorded steps."""
        return len(self.observations)
    
    def get_observations_array(self) -> np.ndarray:
        """Return post-step observations as a 2D array (steps, obs_dim)."""
        if not self.observations:
            return np.array([])
        return np.stack(self.observations)

    def get_pre_observations_array(self) -> np.ndarray:
        """Return pre-action observations as a 2D array (steps, obs_dim)."""
        if not self.pre_observations:
            return np.array([])
        return np.stack(self.pre_observations)

    def get_complete_observations_array(self) -> np.ndarray:
        """Return the full state trajectory: initial observation plus post-step values."""
        post = self.get_observations_array()
        pre = self.get_pre_observations_array()
        if post.size == 0:
            return post
        if pre.size == 0:
            return post
        return np.concatenate([pre[:1], post], axis=0)
    
    def get_actions_array(self) -> np.ndarray:
        """Return actions as an array."""
        if not self.actions:
            return np.array([])
        return np.array(self.actions)
    
    def get_rewards_array(self) -> np.ndarray:
        """Return rewards as a 1D array."""
        return np.array(self.rewards, dtype=np.float32)
    
    def get_errors_array(self) -> np.ndarray:
        """Return errors as a 2D array (steps, error_dim)."""
        if not self.errors:
            return np.array([])
        return np.stack(self.errors)
    
    def get_layer_activations_array(self, layer_name: str) -> np.ndarray:
        """Return activations for a specific layer as a 2D array (steps, units)."""
        if layer_name not in self.layer_activations:
            raise ValueError(f"Layer '{layer_name}' not found in history. Available: {list(self.layer_activations.keys())}")
        return np.stack(self.layer_activations[layer_name])
    
    def get_error_levels(self) -> Dict[str, np.ndarray]:
        """Extract per-level error arrays from the concatenated error signal.
        
        Returns dict mapping level names (e.g. 'CL00', 'CL01') to arrays
        of shape (steps, units_at_level). Requires layer_activations to
        contain comparator layer data, otherwise splits error array evenly.
        """
        # If we have comparator layer activations, use those directly
        cl_layers = {k: v for k, v in self.layer_activations.items() if k.startswith('CL')}
        if cl_layers:
            return {k: np.stack(v) for k, v in sorted(cl_layers.items())}
        
        # Fallback: return the full error array as a single level
        errors = self.get_errors_array()
        if errors.size == 0:
            return {}
        return {'errors': errors}


# %% ../nbs/02_individual_utils.ipynb #b57297a2
# Mapping of legacy environment names to their current Gymnasium equivalents.
_LEGACY_ENV_NAME_FIXES: Dict[str, str] = {
    "LunarLanderContinuous-v2": "LunarLanderContinuous-v3",
}


def _current_smooth_factors_from_model(self) -> Dict[str, Any]:
    """Return smooth_factors reflecting current trainable smooth-layer weights.

    ``self.smooth_factors`` records constructor values.  During evolution the
    Keras ``*_smooth`` layer weights are what actually mutate, so saved configs
    and Comet assets should report those current values in
    ``hierarchy.smooth_factors``.
    """
    factors = _to_serializable(getattr(self, "smooth_factors", None))
    if not isinstance(factors, dict) or self.model is None:
        return factors

    factors = {
        "perception": list(factors.get("perception", [])),
        "reference": list(factors.get("reference", [])),
        "output": list(factors.get("output", [])),
        "actions": factors.get("actions", 0.5),
    }
    role_prefixes = {"perception": "PL", "reference": "RL", "output": "OL"}
    activation_funcs = getattr(self, "activation_funcs", {})

    for role, prefix in role_prefixes.items():
        role_activations = activation_funcs.get(role, []) if isinstance(activation_funcs, dict) else []
        for level_idx in range(len(getattr(self, "levels", []) or [])):
            if level_idx >= len(role_activations) or role_activations[level_idx] != "smooth":
                continue
            layer_name = f"{prefix}{level_idx:02d}_smooth"
            try:
                layer = self.model.get_layer(layer_name)
                weights = layer.get_weights()
            except Exception:
                continue
            if weights:
                while len(factors[role]) <= level_idx:
                    factors[role].append(0.5)
                factors[role][level_idx] = _to_serializable(weights[0])

    if isinstance(activation_funcs, dict) and activation_funcs.get("actions") == "smooth":
        try:
            layer = self.model.get_layer("Actions_smooth")
            weights = layer.get_weights()
        except Exception:
            weights = []
        if weights:
            factors["actions"] = _to_serializable(weights[0])

    return factors


def _config_impl(self) -> Dict[str, Any]:
    """Return complete configuration dictionary."""
    if self.model is None:
        raise RuntimeError("Individual must be compiled before exporting config")

    self._store_weights()

    weights = {}
    biases = {}
    layer_parameters = {}
    for layer in self.model.layers:
        layer_weights = layer.get_weights()
        if len(layer_weights) > 0:
            weights[layer.name] = _to_serializable(layer_weights[0])
        if getattr(layer, "bias", None) is not None and len(layer_weights) > 1:
            biases[layer.name] = _to_serializable(layer_weights[1])
        if hasattr(layer, "range_val") and hasattr(layer, "slope"):
            layer_parameters[layer.name] = {
                "range_val": _to_serializable(layer_weights[0]),
                "slope": _to_serializable(layer_weights[1]),
            }

    config = {
        "env_name": self.env_name,
        "env_properties": _to_serializable(self.env_properties),
        "hierarchy": {
            "levels": list(self.levels),
            "activation_funcs": _to_serializable(self.activation_funcs),
            "smooth_factors": _current_smooth_factors_from_model(self),
            "weight_types": _to_serializable(self.weight_types),
            "obs_connection_level": int(self.obs_connection_level),
            "top_reference_weight_init": getattr(self, "top_reference_weight_init", "ones"),
            "reference_values": _to_serializable(getattr(self, "reference_values", [])),
            "evolve_references": bool(getattr(self, "evolve_references", False)),
            "top_level_obs_indices": _to_serializable(getattr(self, "top_level_obs_indices", None)),
            "zerolevel_inputs_indexes": _to_serializable(getattr(self, "zerolevel_inputs_indexes", None)),
        },
        "weights": weights,
        "biases": biases,
        "layer_parameters": layer_parameters,
        "fixed_weights": sorted(list(getattr(self, "fixed_weights", set()))),
        "fixed_levels": sorted(list(getattr(self, "fixed_levels", set()))),
        "metadata": {
            "created": datetime.now(timezone.utc).isoformat(),
            "fitness": _to_serializable(self.fitness),
            "fitness_method": _to_serializable(getattr(self, "fitness_method", None)),
            "fitness_source": _to_serializable(getattr(self, "fitness_source", None)),
            "fitness_observation_indices": _to_serializable(getattr(self, "fitness_observation_indices", None)),
            "fitness_targets": _to_serializable(getattr(self, "fitness_targets", None)),
            "run_steps": _to_serializable(getattr(self, "run_steps", 0)),
            "total_reward": _to_serializable(getattr(self, "total_reward", 0.0)),
            "last_reward": _to_serializable(getattr(self, "last_reward", None)),
            "success": _to_serializable(getattr(self, "success", False)),
            "random_seed": _to_serializable(self.random_seed),
        },
    }

    return config




# %% ../nbs/02_individual_utils.ipynb #e80bf29b
def _save_config_impl(self, filepath: str, format: str = "json") -> None:
    """Save configuration to JSON or pickle file."""
    config = self.config()
    file_path = Path(filepath)
    file_path.parent.mkdir(parents=True, exist_ok=True)

    fmt = format.lower()
    if fmt == "json":
        with open(file_path, "w", encoding="utf-8") as f:
            json.dump(config, f, indent=2)
    elif fmt in {"pickle", "pkl"}:
        with open(file_path, "wb") as f:
            pickle.dump(config, f)
    else:
        raise ValueError(f"Unknown format '{format}'. Use 'json' or 'pickle'.")


def _load_config_impl(cls, filepath: str) -> Dict[str, Any]:
    """Load configuration dictionary from JSON or pickle file."""
    file_path = Path(filepath)
    suffix = file_path.suffix.lower()
    if suffix in {".pkl", ".pickle"}:
        with open(file_path, "rb") as f:
            return pickle.load(f)

    with open(file_path, "r", encoding="utf-8") as f:
        return json.load(f)



# %% ../nbs/02_individual_utils.ipynb #16b09efc
def _infer_smooth_factors_from_saved_weights(
    hierarchy: Dict[str, Any], weights: Dict[str, Any]
) -> Optional[Dict[str, Any]]:
    """Infer per-layer smooth factors for configs saved before they were explicit.

    Older ``--save-config`` output stored trainable ``*_smooth`` layer weights but
    did not store ``hierarchy.smooth_factors``.  Reconstructing such a config with
    default scalar smooth factors builds scalar ``smooth_factor`` variables, while
    the saved weights may be vectors (for example ``[0.1, 0.2]`` for a 2-unit
    layer).  Passing the saved values back as constructor smooth factors recreates
    the original variable shapes before ``set_weights`` runs.
    """
    activation_funcs = hierarchy.get("activation_funcs", "linear")
    levels = hierarchy.get("levels", [])
    if not isinstance(activation_funcs, dict) or not levels:
        return None

    inferred: Dict[str, Any] = {
        "perception": [0.5] * len(levels),
        "reference": [0.5] * len(levels),
        "output": [0.5] * len(levels),
        "actions": 0.5,
    }
    found = False
    role_prefixes = {
        "perception": "PL",
        "reference": "RL",
        "output": "OL",
    }

    for role, prefix in role_prefixes.items():
        role_activations = activation_funcs.get(role, [])
        for level_idx in range(len(levels)):
            if level_idx >= len(role_activations) or role_activations[level_idx] != "smooth":
                continue
            layer_name = f"{prefix}{level_idx:02d}_smooth"
            if layer_name in weights:
                inferred[role][level_idx] = weights[layer_name]
                found = True

    if activation_funcs.get("actions") == "smooth" and "Actions_smooth" in weights:
        action_value = weights["Actions_smooth"]
        if isinstance(action_value, list):
            inferred["actions"] = float(action_value[0]) if action_value else 0.5
        else:
            inferred["actions"] = float(action_value)
        found = True

    return inferred if found else None


def _from_config_impl(cls, config: Dict[str, Any]) -> "DHPCTIndividual":
    """Create a compiled individual from a configuration dictionary."""
    if "env_name" not in config or "hierarchy" not in config:
        raise KeyError("Config must include 'env_name' and 'hierarchy'")

    hierarchy = config["hierarchy"]
    weights = config.get("weights", {})
    smooth_factors = hierarchy.get("smooth_factors", None)
    if smooth_factors is None:
        smooth_factors = _infer_smooth_factors_from_saved_weights(hierarchy, weights)

    individual = cls(
        env_name=config["env_name"],
        levels=hierarchy["levels"],
        activation_funcs=hierarchy.get("activation_funcs", "linear"),
        weight_types=hierarchy.get("weight_types", "float"),
        fixed_weights=set(config.get("fixed_weights", [])),
        fixed_levels=set(config.get("fixed_levels", [])),
        obs_connection_level=hierarchy.get("obs_connection_level", 0),
        random_seed=config.get("metadata", {}).get("random_seed", None),
        smooth_factors=smooth_factors,
        reference_values=hierarchy.get("reference_values", None),
        evolve_references=hierarchy.get("evolve_references", False),
        top_reference_weight_init=hierarchy.get("top_reference_weight_init", "ones"),
        top_level_obs_indices=hierarchy.get("top_level_obs_indices", None),
        zerolevel_inputs_indexes=hierarchy.get("zerolevel_inputs_indexes", None),
    )
    individual.compile()

    weights = config.get("weights", {})
    biases = config.get("biases", {})
    layer_parameters = config.get("layer_parameters", {})

    for layer in individual.model.layers:
        current = layer.get_weights()
        if len(current) == 0:
            continue

        layer_name = layer.name
        if layer_name not in weights and layer_name not in biases and layer_name not in layer_parameters:
            continue

        if layer_name in layer_parameters and hasattr(layer, "range_val") and hasattr(layer, "slope"):
            params = layer_parameters[layer_name]
            try:
                layer.set_weights([
                    _to_numpy(params.get("range_val", current[0])),
                    _to_numpy(params.get("slope", current[1])),
                ])
            except Exception as exc:
                raise ValueError(f"Failed to restore parameters for layer '{layer_name}': {exc}")
            continue

        new_weights = []
        kernel = _to_numpy(weights[layer_name]) if layer_name in weights else current[0]
        if layer_name == f"RL{len(individual.levels) - 1:02d}":
            # Top-level reference gains are invariant. Ignore evolved/restored
            # values from older configs and keep ReferencesInput pass-through.
            kernel = np.ones_like(current[0], dtype=current[0].dtype)
        elif (
            layer_name == f"PL{len(individual.levels) - 1:02d}"
            and getattr(individual, "top_level_obs_indices", None) is not None
        ):
            # Direct top-level observation perceptions are fixed identity mappings.
            # Ignore older saved/evolved gains (including legacy ElementWise vectors)
            # so top-level comparator error is measured against the raw selected obs.
            kernel = np.eye(
                np.asarray(current[0]).shape[0],
                np.asarray(current[0]).shape[1],
                dtype=current[0].dtype,
            )
        elif (
            layer_name.endswith("_smooth")
            and np.asarray(kernel).shape == ()
            and np.asarray(current[0]).shape != ()
        ):
            # Backward compatibility: older configs may contain a scalar
            # smooth_factor for a whole ExponentialSmoothLayer. Newer models use
            # one smooth_factor per output unit, so broadcast old scalar values
            # to the layer's current vector shape before set_weights().
            kernel = np.full_like(current[0], float(kernel), dtype=current[0].dtype)
        elif (
            layer_name == "PL00"
            and np.asarray(kernel).ndim == 2
            and np.asarray(current[0]).ndim == 2
            and np.asarray(kernel).shape != np.asarray(current[0]).shape
            and np.asarray(kernel).shape[1] == np.asarray(current[0]).shape[1]
        ):
            # Backward compatibility for configs saved before
            # top_level_obs_indices dimensions were excluded from PL00.  Old
            # PL00 kernels may still have rows for the full observation vector;
            # select only the rows that feed the current effective level-0 input.
            effective_indices = getattr(individual, "level0_observation_indices", None)
            if effective_indices is not None:
                original_indices = hierarchy.get("zerolevel_inputs_indexes", None)
                if original_indices is None:
                    obs_shape = individual.env_properties.get("observation_shape", (0,))
                    obs_dim = int(obs_shape[0]) if len(obs_shape) > 0 else np.asarray(kernel).shape[0]
                    original_indices = list(range(obs_dim))
                original_indices = [int(idx) for idx in original_indices]
                row_positions = [
                    original_indices.index(int(idx))
                    for idx in effective_indices
                    if int(idx) in original_indices
                ]
                if len(row_positions) == np.asarray(current[0]).shape[0]:
                    kernel = np.asarray(kernel)[row_positions, :]
        new_weights.append(kernel)

        if len(current) > 1:
            bias = _to_numpy(biases[layer_name]) if layer_name in biases else current[1]
            new_weights.append(bias)

        try:
            layer.set_weights(new_weights)
        except Exception as exc:
            raise ValueError(f"Failed to restore weights for layer '{layer_name}': {exc}")

    individual._store_weights()
    individual.fitness = config.get("metadata", {}).get("fitness", None)
    individual.fitness_method = config.get("metadata", {}).get("fitness_method", None)
    individual.fitness_source = config.get("metadata", {}).get("fitness_source", None)
    individual.fitness_observation_indices = config.get("metadata", {}).get("fitness_observation_indices", None)
    individual.fitness_targets = config.get("metadata", {}).get("fitness_targets", None)
    individual.run_steps = config.get("metadata", {}).get("run_steps", 0)
    individual.total_reward = config.get("metadata", {}).get("total_reward", 0.0)
    individual.last_reward = config.get("metadata", {}).get("last_reward", None)
    individual.success = bool(config.get("metadata", {}).get("success", False))
    return individual



# %% ../nbs/02_individual_utils.ipynb #5e078cc5
def _pct_func_config(
    func_type: str,
    name: str,
    value: float = 0.0,
    links: Optional[List[str]] = None,
    **extra,
 ):
    links_dict = {str(i): link for i, link in enumerate(links or [])}
    payload = {"type": func_type, "name": name, "value": float(value), "links": links_dict}
    for key, val in extra.items():
        payload[key] = _to_serializable(val)
    return payload


def _looks_like_pct_hierarchy_config(config: Dict[str, Any]) -> bool:
    return (
        isinstance(config, dict)
        and config.get("type") in {"PCTHierarchy", "Individual"}
        and "name" in config
        and isinstance(config.get("levels"), dict)
        and "pre" in config
        and "post" in config
    )


def _extract_env_name_from_legacy(config: Dict[str, Any]) -> str:
    env_name = config.get("env_name")
    if isinstance(env_name, str) and env_name:
        return env_name

    pre = config.get("pre", {})
    if isinstance(pre, dict):
        for item in pre.values():
            if isinstance(item, dict):
                candidate = item.get("env_name")
                if isinstance(candidate, str) and candidate:
                    return candidate

    return "CartPole-v1"


def _is_weighted_sum_type(func_type: Any) -> bool:
    return isinstance(func_type, str) and func_type.endswith("WeightedSum")


# %% ../nbs/02_individual_utils.ipynb #0727f4ca
def _legacy_env_type(env_name: str) -> str:
    """Return the legacy pct environment class-style name for a Gymnasium id."""
    if not env_name:
        return "Environment"
    return "".join(part[:1].upper() + part[1:] for part in str(env_name).replace("-", "_").split("_") if part)


def _legacy_smooth_factor_for_slot(smooth_factors: Dict[str, Any], role: str, lvl: int, col: Optional[int] = None) -> float:
    value = smooth_factors.get(role, 0.5)
    if role != "actions" and isinstance(value, list):
        value = value[lvl] if lvl < len(value) else 0.5
    if col is not None and isinstance(value, (list, tuple, np.ndarray)):
        return float(value[col]) if col < len(value) else 0.5
    if isinstance(value, (list, tuple, np.ndarray)):
        return float(value[0]) if len(value) else 0.5
    return float(value)


def _legacy_weight_list(weights: Dict[str, Any], layer_name: str, col: int, length: int, default: float = 1.0) -> List[float]:
    arr = np.array(weights.get(layer_name, []), dtype=np.float32)
    if arr.size == 0:
        return [float(default)] * int(length)
    if arr.ndim == 0:
        return [float(arr)] * int(length)
    if arr.ndim == 1:
        if int(length) == 1 and col < arr.shape[0]:
            return [float(arr[col])]
        vals = arr[: int(length)]
        if vals.shape[0] < int(length):
            vals = np.pad(vals, (0, int(length) - vals.shape[0]), constant_values=default)
        return vals.astype(float).tolist()
    if arr.ndim >= 2:
        if arr.shape[1] > col:
            vals = arr[: int(length), col]
        else:
            vals = np.full(int(length), float(default), dtype=np.float32)
        if vals.shape[0] < int(length):
            vals = np.pad(vals, (0, int(length) - vals.shape[0]), constant_values=default)
        return vals.astype(float).tolist()
    return [float(default)] * int(length)


def _legacy_gain(weights: Dict[str, Any], layer_name: str, col: int, default: float = 1.0) -> float:
    arr = np.array(weights.get(layer_name, []), dtype=np.float32)
    if arr.size == 0:
        return float(default)
    if arr.ndim == 0:
        return float(arr)
    if arr.ndim == 1:
        return float(arr[col]) if col < arr.shape[0] else float(default)
    if arr.ndim >= 2:
        return float(arr[0, col]) if arr.shape[1] > col else float(default)
    return float(default)


def _legacy_weighted_function_config(
    activation: str,
    name: str,
    links: List[str],
    weights: List[float],
    smooth_factor: float = 0.5,
    value: float = 0.0,
) -> Dict[str, Any]:
    """Build the closest legacy pct weighted-function config for a DPCT activation."""
    if activation == "smooth":
        return _pct_func_config(
            "EASmoothWeightedSum",
            name,
            value=value,
            links=links,
            weights=weights,
            smooth_factor=smooth_factor,
        )
    if activation == "sigmoid":
        return _pct_func_config(
            "EASigmoidWeightedSum",
            name,
            value=value,
            links=links,
            weights=weights,
        )
    return _pct_func_config("EAWeightedSum", name, value=value, links=links, weights=weights)


def config_to_legacy_config(
    config: Dict[str, Any],
    *,
    name: Optional[str] = None,
    env_inputs_names: Optional[List[str]] = None,
) -> Dict[str, Any]:
    """Convert a saved ``DHPCTIndividual.config()`` dictionary to legacy pct config.

    The returned dictionary follows the ``PCTHierarchy.get_config()`` structure
    used by the legacy ``pct`` library, including environment ``pre`` nodes,
    hierarchical ``PCTNode`` levels, and action ``post`` nodes.  It is intended
    for ``pct.hierarchy.PCTHierarchy.from_config(...)`` or for embedding as the
    ``config = {...}`` payload in old ``.properties`` files.

    Args:
        config: A dictionary returned by ``DHPCTIndividual.config()`` or loaded
            from a saved DPCT JSON file.
        name: Optional legacy hierarchy name.  Defaults to ``dpct_<env_name>``.
        env_inputs_names: Optional display names for observation inputs.  When
            omitted, names are generated as ``I0``, ``I1``, ... from observation
            indices.

    Returns:
        Legacy pct hierarchy configuration dictionary.
    """
    if not isinstance(config, dict) or "hierarchy" not in config:
        raise ValueError("config must be a DHPCTIndividual.config() dictionary")

    hierarchy = config.get("hierarchy", {})
    levels = [int(x) for x in hierarchy.get("levels", [])]
    if not levels:
        raise ValueError("config['hierarchy']['levels'] must contain at least one level")

    env_name = str(config.get("env_name", "CartPole-v1"))
    env_type = _legacy_env_type(env_name)
    env_props = config.get("env_properties", {}) or {}
    obs_shape = env_props.get("observation_shape") or env_props.get("observation_space_shape") or []
    action_shape = env_props.get("action_shape") or []
    obs_dim = int(obs_shape[0]) if len(obs_shape) > 0 else 0
    action_dim = int(action_shape[0]) if len(action_shape) > 0 else 1

    activation_funcs = hierarchy.get("activation_funcs", {}) or {}
    smooth_factors = hierarchy.get("smooth_factors", {}) or {}
    weights = config.get("weights", {}) or {}
    reference_values = np.array(hierarchy.get("reference_values", []), dtype=np.float32).reshape(-1)
    top_obs = hierarchy.get("top_level_obs_indices")
    zero_inputs = hierarchy.get("zerolevel_inputs_indexes")

    if obs_dim <= 0:
        pl00 = np.array(weights.get("PL00", []), dtype=np.float32)
        obs_dim = int(pl00.shape[0]) if pl00.ndim >= 2 else int(levels[0])

    if top_obs is not None:
        top_obs = [int(idx) for idx in top_obs]
        level0_indices = [int(idx) for idx in (zero_inputs if zero_inputs is not None else range(obs_dim)) if int(idx) not in set(top_obs)]
    else:
        level0_indices = [int(idx) for idx in (zero_inputs if zero_inputs is not None else range(obs_dim))]

    all_input_indices = []
    for idx in list(level0_indices) + (list(top_obs) if top_obs is not None else []):
        if idx not in all_input_indices:
            all_input_indices.append(idx)
    if not all_input_indices:
        all_input_indices = list(range(obs_dim))

    if env_inputs_names is None:
        input_names = {idx: f"I{idx}" for idx in all_input_indices}
    else:
        if len(env_inputs_names) != len(all_input_indices):
            raise ValueError("env_inputs_names length must match the number of used observation indices")
        input_names = {idx: str(label) for idx, label in zip(all_input_indices, env_inputs_names)}

    pre = {
        "pre0": {
            "type": env_type,
            "name": env_type,
            "value": [0.0] * (obs_dim + action_dim),
            "links": {str(i): f"Action{i + 1}" for i in range(action_dim)},
            "env_name": env_name,
            "reward": 0,
            "done": False,
            "info": {},
        }
    }
    for pre_idx, obs_idx in enumerate(all_input_indices, start=1):
        pre[f"pre{pre_idx}"] = {
            "type": "IndexedParameter",
            "name": input_names[obs_idx],
            "value": 0.0,
            "links": {"0": env_type},
            "index": int(obs_idx),
        }

    pct_levels: Dict[str, Any] = {}
    for lvl, units in enumerate(levels):
        nodes: Dict[str, Any] = {}
        for col in range(int(units)):
            per_name = f"PL{lvl:02d}C{col:02d}"
            ref_name = f"RL{lvl:02d}C{col:02d}"
            com_name = f"CL{lvl:02d}C{col:02d}"
            out_name = f"OL{lvl:02d}C{col:02d}"

            per_activation = activation_funcs.get("perception", ["linear"] * len(levels))[lvl]
            ref_activation = activation_funcs.get("reference", ["linear"] * len(levels))[lvl]
            out_activation = activation_funcs.get("output", ["linear"] * len(levels))[lvl]

            if lvl == 0:
                per_links = [input_names[idx] for idx in level0_indices]
                per_weights = _legacy_weight_list(weights, f"PL{lvl:02d}", col, len(per_links), default=1.0)
            elif lvl == len(levels) - 1 and top_obs is not None:
                obs_idx = top_obs[col]
                per_links = [input_names[obs_idx]]
                per_weights = [1.0]
            else:
                per_links = [f"PL{lvl - 1:02d}C{i:02d}" for i in range(int(levels[lvl - 1]))]
                per_weights = _legacy_weight_list(weights, f"PL{lvl:02d}", col, len(per_links), default=1.0)
            per_cfg = _legacy_weighted_function_config(
                per_activation,
                per_name,
                per_links,
                per_weights,
                _legacy_smooth_factor_for_slot(smooth_factors, "perception", lvl, col),
            )

            if lvl == len(levels) - 1:
                ref_value = float(reference_values[col]) if col < reference_values.shape[0] else 0.0
                ref_cfg = _pct_func_config("EAConstant", ref_name, value=ref_value, links=[])
            else:
                ref_links = [f"OL{lvl + 1:02d}C{i:02d}" for i in range(int(levels[lvl + 1]))]
                ref_weights = _legacy_weight_list(weights, f"RL{lvl:02d}", col, len(ref_links), default=1.0)
                ref_cfg = _legacy_weighted_function_config(
                    ref_activation,
                    ref_name,
                    ref_links,
                    ref_weights,
                    _legacy_smooth_factor_for_slot(smooth_factors, "reference", lvl, col),
                )

            com_cfg = _pct_func_config("Subtract", com_name, value=0.0, links=[ref_name, per_name])
            gain = _legacy_gain(weights, f"OL{lvl:02d}", col, default=1.0)
            if out_activation == "smooth":
                out_cfg = _legacy_weighted_function_config(
                    out_activation,
                    out_name,
                    [com_name],
                    [gain],
                    _legacy_smooth_factor_for_slot(smooth_factors, "output", lvl, col),
                )
            elif out_activation == "sigmoid":
                out_cfg = _legacy_weighted_function_config(out_activation, out_name, [com_name], [gain])
            else:
                out_cfg = _pct_func_config("EAProportional", out_name, value=0.0, links=[com_name], gain=gain)

            node_cfg = {
                "type": "PCTNode",
                "name": f"L{lvl}C{col}",
                "refcoll": {"0": ref_cfg},
                "percoll": {"0": per_cfg},
                "comcoll": {"0": com_cfg},
                "outcoll": {"0": out_cfg},
            }
            nodes[f"col{col}"] = {"col": col, "node": node_cfg}
        pct_levels[f"level{lvl}"] = {"level": lvl, "nodes": nodes}

    action_activation = activation_funcs.get("actions", "linear")
    post: Dict[str, Any] = {}
    action_links = [f"OL00C{i:02d}" for i in range(int(levels[0]))]
    action_weights = np.array(weights.get("Actions", []), dtype=np.float32)
    for action_idx in range(action_dim):
        if action_weights.ndim >= 2 and action_weights.shape[1] > action_idx:
            aw = action_weights[: int(levels[0]), action_idx].astype(float).tolist()
        elif action_weights.ndim == 1 and action_dim == 1:
            aw = action_weights[: int(levels[0])].astype(float).tolist()
        else:
            aw = [1.0] * int(levels[0])
        post_name = f"Action{action_idx + 1}"
        if action_activation == "smooth":
            post_cfg = _legacy_weighted_function_config(
                action_activation,
                post_name,
                action_links,
                aw,
                _legacy_smooth_factor_for_slot(smooth_factors, "actions", 0, action_idx),
            )
        elif action_activation == "sigmoid":
            post_cfg = _legacy_weighted_function_config(action_activation, post_name, action_links, aw)
        else:
            post_cfg = _pct_func_config("EAWeightedSum", post_name, value=0.0, links=action_links, weights=aw)
        post[f"post{action_idx}"] = post_cfg

    return {
        "type": "PCTHierarchy",
        "name": name or f"dpct_{env_name}",
        "pre": pre,
        "levels": pct_levels,
        "post": post,
    }


def _to_legacy_config_impl(self) -> Dict[str, Any]:
    """Convert this individual to legacy pct ``PCTHierarchy.get_config()`` format."""
    return config_to_legacy_config(self.config())


# %% ../nbs/02_individual_utils.ipynb #c82f8c4f
def _extract_pct_levels(config: Dict[str, Any]) -> List[int]:
    levels_dict = config["levels"]
    ordered = sorted(levels_dict.values(), key=lambda item: int(item.get("level", 0)))
    return [len(level_info.get("nodes", {})) for level_info in ordered]


def _safe_node_get(config: Dict[str, Any], lvl: int, col: int) -> Dict[str, Any]:
    return config["levels"][f"level{lvl}"]["nodes"][f"col{col}"]["node"]


# %% ../nbs/02_individual_utils.ipynb #d5ac8288
def _legacy_func_cfg(config: Dict[str, Any], lvl: int, col: int, coll_name: str) -> Dict[str, Any]:
    """Return one legacy node function config, or an empty dict when absent."""
    node_cfg = _safe_node_get(config, lvl, col)
    return node_cfg.get(coll_name, {}).get("0", {})


def _legacy_func_activation(func_cfg: Dict[str, Any]) -> str:
    """Map legacy PCT function type to the closest DPCT activation name."""
    func_type = func_cfg.get("type", "") or ""
    if "Sigmoid" in func_type:
        return "sigmoid"
    if "SmoothWeightedSum" in func_type:
        return "smooth"
    return "linear"


def _legacy_func_smooth_factor(func_cfg: Dict[str, Any]) -> float:
    """Extract a legacy smooth factor, defaulting to DPCT's smooth default."""
    if _legacy_func_activation(func_cfg) != "smooth":
        return 0.5
    return float(func_cfg.get("smooth_factor", 0.5))


def _extract_legacy_activation_and_smooth(
    legacy_config: Dict[str, Any], levels: List[int]
) -> tuple[Dict[str, Any], Dict[str, Any]]:
    """Infer DPCT activation/smooth-factor settings from legacy PCT nodes.

    DPCT smooth layers support either scalar or per-unit smooth factors, so
    legacy EASmoothWeightedSum columns keep their individual smooth factors
    instead of being silently downgraded to plain linear layers.
    """
    role_to_coll = {
        "perception": "percoll",
        "reference": "refcoll",
        "output": "outcoll",
    }
    activation_funcs = {
        "perception": [],
        "reference": [],
        "output": [],
        "actions": "linear",
    }
    smooth_factors = {
        "perception": [],
        "reference": [],
        "output": [],
        "actions": 0.5,
    }

    for lvl, units in enumerate(levels):
        # Use the first node with a config for each role; all current DPCT layers
        # are level-wide, not per-column.
        for role, coll_name in role_to_coll.items():
            selected = {}
            selected_factors = []
            for col in range(units):
                candidate = _legacy_func_cfg(legacy_config, lvl, col, coll_name)
                if candidate and not selected:
                    selected = candidate
                selected_factors.append(_legacy_func_smooth_factor(candidate))
            activation = _legacy_func_activation(selected)
            activation_funcs[role].append(activation)
            if activation == "smooth":
                smooth_factors[role].append(selected_factors)
            else:
                smooth_factors[role].append(0.5)

    post = legacy_config.get("post", {})
    first_post = next((post[key] for key in sorted(post)), {}) if post else {}
    activation_funcs["actions"] = _legacy_func_activation(first_post)
    smooth_factors["actions"] = _legacy_func_smooth_factor(first_post)
    return activation_funcs, smooth_factors


def _legacy_weight_for_link(func_cfg: Dict[str, Any], link_name: str, default: float = 1.0) -> float:
    """Return the legacy weight corresponding to a named link."""
    links = func_cfg.get("links", {}) or {}
    weights = func_cfg.get("weights", None)
    if weights is None:
        return default
    for link_idx, link_key in enumerate(sorted(links, key=lambda k: int(k))):
        if links[link_key] == link_name and link_idx < len(weights):
            return float(weights[link_idx])
    return default


def _legacy_first_weight(func_cfg: Dict[str, Any], default: float = 1.0) -> float:
    weights = func_cfg.get("weights", None)
    if weights is None or len(weights) == 0:
        return default
    return float(weights[0])


def _legacy_output_weight(func_cfg: Dict[str, Any], default: float = 1.0) -> float:
    """Extract a legacy output gain from Proportional or WeightedSum configs."""
    if func_cfg.get("gain") is not None:
        return float(func_cfg["gain"])
    return _legacy_first_weight(func_cfg, default=default)


def _from_pct_legacy_config_impl(cls, legacy_config: Dict[str, Any]) -> "DHPCTIndividual":
    levels = _extract_pct_levels(legacy_config)
    env_name = _extract_env_name_from_legacy(legacy_config)

    # Patch deprecated Gymnasium environment names
    env_name = _LEGACY_ENV_NAME_FIXES.get(env_name, env_name)

    activation_funcs, smooth_factors = _extract_legacy_activation_and_smooth(
        legacy_config, levels
    )

    reference_values = legacy_config.get("references")
    if reference_values is None:
        top_level = len(levels) - 1
        reference_values = []
        for col in range(levels[-1]):
            ref_cfg = _legacy_func_cfg(legacy_config, top_level, col, "refcoll")
            if ref_cfg.get("value") is not None and not _is_weighted_sum_type(ref_cfg.get("type")):
                reference_values.append(float(ref_cfg["value"]))
            else:
                reference_values.append(0.0)

    individual = cls(
        env_name=env_name,
        levels=levels,
        activation_funcs=activation_funcs,
        smooth_factors=smooth_factors,
        weight_types="float",
        random_seed=None,
        reference_values=reference_values,
        top_level_obs_indices=legacy_config.get("toplevel_inputs_indexes"),
        zerolevel_inputs_indexes=legacy_config.get("zerolevel_inputs_indexes"),
    )
    individual.compile()

    for lvl, units in enumerate(levels):
        # Transfer perception weights.
        pl_layer = individual.model.get_layer(f"PL{lvl:02d}")
        pl_current = pl_layer.get_weights()
        if lvl == len(levels) - 1 and getattr(individual, "top_level_obs_indices", None) is not None:
            # Current direct top-level observation perception is fixed identity.
            # Do not import legacy/evolved perception gains or smooth state for this path.
            pass
        elif len(pl_current) > 0 and pl_current[0].ndim == 1:
            # ElementWiseMultiplyLayer — one-to-one gathered observation mapping.
            per_weights_1d = np.ones(units, dtype=np.float32)
            for col in range(units):
                per_cfg = _legacy_func_cfg(legacy_config, lvl, col, "percoll")
                if _is_weighted_sum_type(per_cfg.get("type")):
                    per_weights_1d[col] = _legacy_first_weight(per_cfg)
            pl_layer.set_weights([per_weights_1d])
        elif lvl == 0:
            # Level-0 Dense sees either the full observation vector or the gathered
            # zerolevel subset.  Legacy weights are positional over their links, so
            # build the actual Dense input kernel directly rather than writing into
            # absolute observation rows and gathering afterward.
            if getattr(individual, "zerolevel_inputs_indexes", None) is not None:
                input_dim = len(individual.zerolevel_inputs_indexes)
            else:
                obs_shape = individual.env_properties.get("observation_shape", (0,))
                input_dim = int(obs_shape[0]) if len(obs_shape) > 0 else 0
            per_kernel = np.zeros((input_dim, units), dtype=np.float32)
            for col in range(units):
                per_cfg = _legacy_func_cfg(legacy_config, lvl, col, "percoll")
                if _is_weighted_sum_type(per_cfg.get("type")):
                    weights = np.array(per_cfg.get("weights", [1.0] * input_dim), dtype=np.float32).reshape(-1)
                    limit = min(input_dim, weights.shape[0])
                    per_kernel[:limit, col] = weights[:limit]
            if len(pl_current) > 0:
                new_weights = [per_kernel]
                if len(pl_current) > 1:
                    new_weights.append(np.array(pl_current[1], dtype=np.float32))
                pl_layer.set_weights(new_weights)
        else:
            prev_units = levels[lvl - 1]
            per_kernel = np.zeros((prev_units, units), dtype=np.float32)
            for col in range(units):
                per_cfg = _legacy_func_cfg(legacy_config, lvl, col, "percoll")
                if _is_weighted_sum_type(per_cfg.get("type")):
                    weights = np.array(per_cfg.get("weights", [1.0] * prev_units), dtype=np.float32).reshape(-1)
                    limit = min(prev_units, weights.shape[0])
                    per_kernel[:limit, col] = weights[:limit]
            if len(pl_current) > 0:
                new_weights = [per_kernel]
                if len(pl_current) > 1:
                    new_weights.append(np.array(pl_current[1], dtype=np.float32))
                pl_layer.set_weights(new_weights)

        # Transfer lower-level reference weights from higher output links.
        if lvl < len(levels) - 1:
            next_units = levels[lvl + 1]
            ref_kernel = np.zeros((next_units, units), dtype=np.float32)
            for col in range(units):
                ref_cfg = _legacy_func_cfg(legacy_config, lvl, col, "refcoll")
                if _is_weighted_sum_type(ref_cfg.get("type")):
                    weights = np.array(ref_cfg.get("weights", [1.0] * next_units), dtype=np.float32).reshape(-1)
                    limit = min(next_units, weights.shape[0])
                    ref_kernel[:limit, col] = weights[:limit]
            rl_layer = individual.model.get_layer(f"RL{lvl:02d}")
            rl_current = rl_layer.get_weights()
            if len(rl_current) > 0:
                new_weights = [ref_kernel]
                if len(rl_current) > 1:
                    new_weights.append(np.array(rl_current[1], dtype=np.float32))
                rl_layer.set_weights(new_weights)

        # Transfer top-level reference values where the architecture has a bias.
        # For the normal ElementWise top-level reference layer, reference values
        # live in individual.reference_values and are supplied through the model's
        # ReferencesInput during execution.
        if lvl == len(levels) - 1:
            rl_layer = individual.model.get_layer(f"RL{lvl:02d}")
            rl_current = rl_layer.get_weights()
            if len(rl_current) >= 2:
                bias = np.array(rl_current[1], dtype=np.float32)
                for col in range(units):
                    ref_cfg = _legacy_func_cfg(legacy_config, lvl, col, "refcoll")
                    if ref_cfg.get("type") in ("Variable", "EAVariable", "Constant", "EAConstant") and ref_cfg.get("value") is not None:
                        bias[col] = float(ref_cfg["value"])
                rl_layer.set_weights([rl_current[0], bias])

        # Transfer output gains/weights to OL## ElementWiseMultiplyLayer weights.
        try:
            ol_layer = individual.model.get_layer(f"OL{lvl:02d}")
            ol_current = ol_layer.get_weights()
            if len(ol_current) > 0:
                gain_weights = np.ones(units, dtype=np.float32)
                for col in range(units):
                    out_cfg = _legacy_func_cfg(legacy_config, lvl, col, "outcoll")
                    gain_weights[col] = _legacy_output_weight(out_cfg)
                ol_layer.set_weights([gain_weights])
        except ValueError:
            pass

    # T154: Transfer post-action weights to Actions layer.
    # Try both "Actions_final" (older builds) and "Actions" (current builds).
    post = legacy_config.get("post", {})
    if post:
        actions_layer = None
        for candidate in ("Actions_final", "Actions"):
            try:
                actions_layer = individual.model.get_layer(candidate)
                break
            except ValueError:
                pass

        if actions_layer is not None:
            actions_current = actions_layer.get_weights()
            if len(actions_current) > 0:
                kernel_shape = actions_current[0].shape  # (num_OL_units, num_actions)
                pw = np.zeros(kernel_shape, dtype=np.float32)
                num_ol_units = kernel_shape[0]
                import re as _re
                for action_idx, pk in enumerate(sorted(post)):
                    pv = post[pk]
                    if not _is_weighted_sum_type(pv.get("type", "")):
                        continue
                    weights_list = pv.get("weights")
                    links = pv.get("links", {})
                    if weights_list is None:
                        continue
                    for link_idx, link_key in enumerate(sorted(links, key=lambda k: int(k))):
                        link_name = links[link_key]
                        m = _re.search(r'C(\d+)', link_name)
                        if m:
                            ol_col = int(m.group(1))
                        else:
                            ol_col = link_idx
                        if ol_col < num_ol_units and link_idx < len(weights_list):
                            pw[ol_col, action_idx] = float(weights_list[link_idx])
                new_weights = [pw]
                if len(actions_current) > 1:
                    new_weights.append(actions_current[1])
                actions_layer.set_weights(new_weights)

    # Transfer per-action sigmoid range/slope from legacy EASigmoidWeightedSum
    if activation_funcs.get("actions") == "sigmoid":
        try:
            sigmoid_layer = individual.model.get_layer("Actions_sigmoid")
        except ValueError:
            sigmoid_layer = None
        if sigmoid_layer is not None:
            num_actions = len(sorted(post))
            range_vals = np.full(num_actions, 2.0, dtype=np.float32)
            slope_vals = np.full(num_actions, 10.0, dtype=np.float32)
            for action_idx, pk in enumerate(sorted(post)):
                pv = post[pk]
                if "Sigmoid" in (pv.get("type", "") or ""):
                    if pv.get("range") is not None:
                        range_vals[action_idx] = float(pv["range"])
                    if pv.get("slope") is not None:
                        slope_vals[action_idx] = float(pv["slope"])
            sigmoid_layer.set_weights([range_vals, slope_vals])

    # Apply explicit references override (e.g. from .properties file) to the
    # executable reference input values.  Do not warn for ElementWise top-level
    # reference layers: they intentionally multiply the ReferencesInput values.
    if "references" in legacy_config:
        refs = np.array(legacy_config["references"], dtype=np.float32)
        if refs.shape[0] != levels[-1]:
            raise ValueError(
                f"references length ({refs.shape[0]}) must match top-level units ({levels[-1]})"
            )
        individual.reference_values = refs

    individual._store_weights()
    return individual


# %% ../nbs/02_individual_utils.ipynb #a868c5ea
def _from_legacy_config_impl(cls, legacy_config: Dict[str, Any]) -> "DHPCTIndividual":
    """Create individual from exact PCTHierarchy config or old flat DPCT legacy format."""
    if _looks_like_pct_hierarchy_config(legacy_config):
        return _from_pct_legacy_config_impl(cls, legacy_config)

    if "env_name" not in legacy_config or "levels" not in legacy_config:
        raise ValueError("Unsupported legacy configuration format")

    converted = {
        "env_name": legacy_config["env_name"],
        "hierarchy": {
            "levels": legacy_config["levels"],
            "activation_funcs": legacy_config.get("activation_funcs", "linear"),
            "weight_types": legacy_config.get("weight_types", "float"),
            "obs_connection_level": legacy_config.get("obs_connection_level", 0),
        },
        "weights": legacy_config.get("weights", {}),
        "biases": legacy_config.get("biases", {}),
        "fixed_weights": legacy_config.get("fixed_weights", []),
        "fixed_levels": legacy_config.get("fixed_levels", []),
        "metadata": {
            "fitness": legacy_config.get("fitness", None),
            "random_seed": legacy_config.get("random_seed", None),
        },
    }

    if "toplevel_inputs_indexes" in legacy_config:
        converted["hierarchy"]["top_level_obs_indices"] = legacy_config["toplevel_inputs_indexes"]

    if "zerolevel_inputs_indexes" in legacy_config:
        converted["hierarchy"]["zerolevel_inputs_indexes"] = legacy_config["zerolevel_inputs_indexes"]

    if "references" in legacy_config:
        converted["hierarchy"]["reference_values"] = legacy_config["references"]

    return cls.from_config(converted)

# %% ../nbs/02_individual_utils.ipynb #13b40f3b
import ast as _ast
import re as _re_mod


def _parse_properties_file(filepath: str) -> Dict[str, Any]:
    """Parse a legacy PCT .properties file.

    Extracts the ``config = {...}`` Python dict literal and any scalar
    key-value properties (e.g. ``toplevel_inputs_indexes``, ``references``).
    """
    text = Path(filepath).read_text(encoding="utf-8")

    # Extract the config dict literal
    m = _re_mod.search(r'^config\s*=\s*', text, _re_mod.MULTILINE)
    if m is None:
        raise ValueError(f"No 'config = ...' line found in {filepath}")
    config_str = text[m.end():]
    # The dict may span one (very long) line; take until end of line
    config_line_end = config_str.find('\n')
    if config_line_end != -1:
        config_str = config_str[:config_line_end]
    config = _ast.literal_eval(config_str.strip())

    # Extract simple properties
    props: Dict[str, Any] = {"config": config}
    for key in ("toplevel_inputs_indexes", "zerolevel_inputs_indexes", "references"):
        pm = _re_mod.search(rf'^{key}\s*=\s*(.+)$', text, _re_mod.MULTILINE)
        if pm:
            raw = pm.group(1).strip()
            if raw.lower() == "none":
                continue
            props[key] = _ast.literal_eval(raw)

    return props


def _load_from_legacy_config_impl(cls, filepath: str) -> "DHPCTIndividual":
    """Load a legacy .properties config file and create an individual from it."""
    data = _parse_properties_file(filepath)
    config = data["config"]

    if "toplevel_inputs_indexes" in data:
        config["toplevel_inputs_indexes"] = data["toplevel_inputs_indexes"]

    if "zerolevel_inputs_indexes" in data:
        config["zerolevel_inputs_indexes"] = data["zerolevel_inputs_indexes"]

    if "references" in data:
        config["references"] = data["references"]

    return _from_legacy_config_impl(cls, config)
