"""Hierarchical Perceptual Control Theory individual with Keras model compilation and environment execution

Docs: https://perceptualrobots.github.io/dpctindividual.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_individual.ipynb.

# %% auto #0
__all__ = ['DHPCTIndividual']

# %% ../nbs/00_individual.ipynb #26b0171d
import os
os.environ.setdefault("TF_CPP_MIN_LOG_LEVEL", "2")
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.utils import set_random_seed
import gymnasium as gym
import json
import pickle
import copy
import random
from typing import Optional, Union, Callable, Dict, List, Set, Any
from .layers import ElementWiseMultiplyLayer, ExponentialSmoothLayer, SigmoidLayer
 
# Optional legacy pct compatibility import
try:
    import pct.errors
    PCT_AVAILABLE = True
except ImportError:
    PCT_AVAILABLE = False

# %% ../nbs/00_individual.ipynb #b1d9567a
class DHPCTIndividual:
    """
    Represents a hierarchical Perceptual Control Theory system with Keras model.
    
    This class manages the creation, compilation, execution, and evolution of
    hierarchical control systems following PCT principles.
    """
    
    @staticmethod
    def _expand_activation_funcs(
        activation_funcs: "Union[str, List[str], Dict[str, Any]]",
        num_levels: int
    ) -> Dict[str, Any]:
        """Expand activation_funcs shorthand to full dict form.
        
        Accepts three input forms and always returns an expanded dict:
          - ``str``: applied uniformly to all function types and levels.
          - ``list[str]``: per-level activation applied to all function types.
          - ``dict``: already in full form; validated and returned as-is.
        
        The returned dict has keys ``"perception"``, ``"reference"``,
        ``"output"`` (each a ``list[str]`` of length *num_levels*) and
        ``"actions"`` (a scalar ``str``).
        
        Args:
            activation_funcs: Raw value from the caller.
            num_levels: ``len(levels)`` — the expected length of per-level lists.
        
        Returns:
            Fully-expanded activation dict.
        
        Raises:
            ValueError: On length mismatch or missing/invalid dict keys.
        """
        func_type_keys = ("perception", "reference", "output")

        # --- str shorthand: broadcast to every slot -------------------------
        if isinstance(activation_funcs, str):
            per_level = [activation_funcs] * num_levels
            return {
                "perception": list(per_level),
                "reference": list(per_level),
                "output": list(per_level),
                "actions": activation_funcs,
            }

        # --- list shorthand: per-level, applied to all function types -------
        if isinstance(activation_funcs, list):
            if len(activation_funcs) != num_levels:
                raise ValueError(
                    f"activation_funcs length ({len(activation_funcs)}) "
                    f"must match levels length ({num_levels})"
                )
            return {
                "perception": list(activation_funcs),
                "reference": list(activation_funcs),
                "output": list(activation_funcs),
                "actions": "linear",  # Actions layer defaults to linear
            }

        # --- dict form: validate and return as-is ---------------------------
        if isinstance(activation_funcs, dict):
            # Check required keys
            for key in func_type_keys:
                if key not in activation_funcs:
                    raise ValueError(f"activation_funcs dict must contain '{key}' key")
                if not isinstance(activation_funcs[key], list):
                    raise ValueError(f"activation_funcs['{key}'] must be a list")
                if len(activation_funcs[key]) != num_levels:
                    raise ValueError(
                        f"activation_funcs['{key}'] length ({len(activation_funcs[key])}) "
                        f"must match levels length ({num_levels})"
                    )
            
            if "actions" not in activation_funcs:
                raise ValueError("activation_funcs dict must contain 'actions' key")
            if not isinstance(activation_funcs["actions"], str):
                raise ValueError("activation_funcs['actions'] must be a string")
            
            # Return a copy to avoid external mutations
            return {
                "perception": list(activation_funcs["perception"]),
                "reference": list(activation_funcs["reference"]),
                "output": list(activation_funcs["output"]),
                "actions": activation_funcs["actions"],
            }

        # --- Invalid input ---------------------------------------------------
        raise ValueError(
            f"activation_funcs must be str, list, or dict; got {type(activation_funcs)}"
        )
    
    @staticmethod
    def _expand_smooth_factors(
        smooth_factors: "Union[None, float, List[float], Dict[str, Any]]",
        activation_funcs: Dict[str, Any],
        num_levels: int
    ) -> Dict[str, Any]:
        """Expand smooth_factors shorthand to full dict form matching activation_funcs structure.
        
        Args:
            smooth_factors: Raw smooth factors specification
            activation_funcs: Already-expanded activation functions dict
            num_levels: Number of levels in hierarchy
            
        Returns:
            Fully-expanded smooth factors dict matching activation_funcs structure
        """
        # None is handled in __init__, where level and action dimensions are
        # available for per-unit random initialization. This fallback is kept for
        # direct helper calls.
        if smooth_factors is None:
            return {
                "perception": [0.5] * num_levels,
                "reference": [0.5] * num_levels, 
                "output": [0.5] * num_levels,
                "actions": 0.5
            }
        
        # Single float: broadcast to all
        if isinstance(smooth_factors, (int, float)):
            factor = float(smooth_factors)
            return {
                "perception": [factor] * num_levels,
                "reference": [factor] * num_levels,
                "output": [factor] * num_levels,
                "actions": factor
            }
        
        # List: per-level applied to all function types
        if isinstance(smooth_factors, list):
            if len(smooth_factors) != num_levels:
                raise ValueError(
                    f"smooth_factors length ({len(smooth_factors)}) "
                    f"must match levels length ({num_levels})"
                )
            return {
                "perception": list(smooth_factors),
                "reference": list(smooth_factors),
                "output": list(smooth_factors),
                "actions": smooth_factors[-1]  # Use last level for actions
            }
        
        # Dict: validate structure matches activation_funcs
        if isinstance(smooth_factors, dict):
            result = {}
            
            for key in ["perception", "reference", "output"]:
                if key in smooth_factors:
                    if not isinstance(smooth_factors[key], list):
                        raise ValueError(f"smooth_factors['{key}'] must be a list")
                    if len(smooth_factors[key]) != num_levels:
                        raise ValueError(
                            f"smooth_factors['{key}'] length ({len(smooth_factors[key])}) "
                            f"must match levels length ({num_levels})"
                        )
                    result[key] = [
                        item if isinstance(item, (list, tuple)) else float(item)
                        for item in smooth_factors[key]
                    ]
                else:
                    # Default to 0.5 for missing keys  
                    result[key] = [0.5] * num_levels
            
            if "actions" in smooth_factors:
                actions_value = smooth_factors["actions"]
                if isinstance(actions_value, (list, tuple)):
                    result["actions"] = list(actions_value)
                elif isinstance(actions_value, (int, float)):
                    result["actions"] = float(actions_value)
                else:
                    raise ValueError("smooth_factors['actions'] must be a number or list")
            else:
                result["actions"] = 0.5
                
            return result
        
        raise ValueError(
            f"smooth_factors must be None, number, list, or dict; got {type(smooth_factors)}"
        )

    @staticmethod
    def _random_smooth_factors(
        levels: List[int],
        activation_funcs: Dict[str, Any],
        action_units: int,
        rng: np.random.Generator,
    ) -> Dict[str, Any]:
        """Create random initial smooth factors for every active smooth layer.

        Each unit in an ``ExponentialSmoothLayer`` receives its own alpha in
        ``[0, 1)``.  Non-smooth slots keep the legacy placeholder value ``0.5``
        because they are not used to build a smooth layer.
        """

        def _role_values(role: str) -> List[Any]:
            values = []
            for level_idx, units in enumerate(levels):
                if activation_funcs[role][level_idx] == "smooth":
                    values.append(rng.uniform(0.0, 1.0, int(units)).astype(np.float32).tolist())
                else:
                    values.append(0.5)
            return values

        if activation_funcs.get("actions") == "smooth":
            action_values = rng.uniform(0.0, 1.0, int(action_units)).astype(np.float32).tolist()
            actions = action_values[0] if int(action_units) == 1 else action_values
        else:
            actions = 0.5

        return {
            "perception": _role_values("perception"),
            "reference": _role_values("reference"),
            "output": _role_values("output"),
            "actions": actions,
        }

    def __init__(
        self,
        env_name: str,
        levels: List[int],
        activation_funcs: Union[str, List[str], Dict[str, Any]] = "linear",
        weight_types: Union[str, List[str]] = "float",
        fixed_weights: Optional[Set[str]] = None,
        fixed_levels: Optional[Set[int]] = None,
        obs_connection_level: int = 0,
        random_seed: Optional[int] = None,
        smooth_factors: Optional[Union[float, Dict[str, Any]]] = None,
        reference_values: Optional[List[float]] = None,
        evolve_references: bool = False,
        top_reference_weight_init: str = "ones",
        top_level_obs_indices: Optional[List[int]] = None,
        zerolevel_inputs_indexes: Optional[List[int]] = None,
    ):
        """
        Initialize a DHPCTIndividual.
        
        Args:
            env_name: Gymnasium environment identifier (e.g., 'CartPole-v1')
            levels: Number of units per level, bottom to top (e.g., [4, 3, 2])
            activation_funcs: Activation function(s). Accepts:
                - str: single activation applied to all function types and levels
                  (e.g., "linear")
                - list[str]: per-level activation applied to all function types
                  (e.g., ["linear", "smooth", "linear"])
                - dict: per-function-type configuration with keys "perception",
                  "reference", "output" (each list[str] per level) and "actions"
                  (scalar str). Valid values: any Keras activation string,
                  "smooth" for ExponentialSmoothLayer, or
                  "sigmoid" for SigmoidLayer.
                Bare string/list shorthand is expanded to full dict form
                internally.
            weight_types: Weight type(s) - 'float', 'boolean', or 'ternary'
            fixed_weights: Set of layer names that should not mutate
            fixed_levels: Set of level indices that should not mutate
            obs_connection_level: Which level receives environment observations (default: 0)
            random_seed: Seed for reproducible weight initialization
            smooth_factors: Smooth factor(s) for ExponentialSmoothLayer when
                activation is "smooth". Accepts:
                - None: smooth layers initialize with random per-unit factors in [0, 1)
                - float: single value applied to all function types and levels
                - dict: per-function-type configuration with keys "perception",
                  "reference", "output" (each list[float] per level) and
                  "actions" (scalar float).
            reference_values: Initial values for the top-level reference input.
                If None, values are randomly initialized in ``[-1, 1]``.
                Must have length equal to ``levels[-1]`` (the top-level unit count).
            evolve_references: If True, reference_values are treated as
                evolvable parameters subject to mutation.
            top_reference_weight_init: Deprecated compatibility argument. Top-level
                reference weights (ReferencesInput -> RL top layer) are always
                fixed at 1.0 and are not evolved.
            top_level_obs_indices: Optional list of observation indices, one per
                top-level perception unit. When provided, each top-level perception
                unit has a single one-to-one connection to the observation at the
                specified index (instead of connecting to the level below).
                Length must equal levels[-1]. Indices must be valid for the
                environment's observation space.
            zerolevel_inputs_indexes: Optional list of observation indices that
                level-0 perception units should connect to.  Only valid when
                ``top_level_obs_indices`` is also provided and there are at
                least two levels.  When set, level-0 perception receives a gathered subset of
                observations at these indices via a fully-connected Dense layer
                instead of the full observation vector.
        
        Raises:
            ValueError: If levels is empty or configuration is invalid
            EnvironmentError: If environment cannot be created
        """
        # Validation
        if not levels or len(levels) == 0:
            raise ValueError("levels must have at least one element")
        if any(l < 1 for l in levels):
            raise ValueError("All level sizes must be >= 1")
        
        # Store parameters
        self.env_name = env_name
        self.levels = levels
        self.obs_connection_level = obs_connection_level
        self.top_level_obs_indices = top_level_obs_indices
        # Ignore zerolevel_inputs_indexes when there is only one level
        self.zerolevel_inputs_indexes = zerolevel_inputs_indexes if len(levels) > 1 else None
        # Filled by compile(): the effective observation indices feeding PL00.
        # When top_level_obs_indices is set, those dimensions are excluded.
        self.level0_observation_indices = None
        self.random_seed = random_seed
        # Keep genome initialization and rollout evaluation seeds distinct.
        # Saved configs restore evaluation_seed for deterministic replay.
        self.evaluation_seed = None
        self._smooth_factors_provided = smooth_factors is not None

        # Validate environment early so action dimensions are available for
        # random per-unit smooth-factor initialization.
        try:
            test_env = gym.make(env_name)
            self.env_properties = {
                'observation_space': str(test_env.observation_space),
                'action_space': str(test_env.action_space),
                'observation_shape': test_env.observation_space.shape,
                'action_shape': test_env.action_space.shape if hasattr(test_env.action_space, 'shape') else (test_env.action_space.n,),
            }
            test_env.close()
        except Exception as e:
            raise EnvironmentError(f"Failed to create environment '{env_name}': {e}")

        if top_reference_weight_init not in {"ones", "weight_type"}:
            raise ValueError(
                "top_reference_weight_init must be 'ones' or 'weight_type'"
            )
        # Retain the attribute for config/backward compatibility, but top-level
        # reference input gains are invariant: ReferencesInput values are the
        # set-points and must reach the top reference comparator unchanged.
        self.top_reference_weight_init = "ones"
        
        # Handle activation functions — always stored as full dict. Top-level
        # reference signals are external set-points and must pass through
        # linearly; lower-level references can still use configured activations.
        self.activation_funcs = self._expand_activation_funcs(activation_funcs, len(levels))
        self.activation_funcs["reference"][-1] = "linear"
        if top_level_obs_indices is not None:
            # Direct top-level observation pathways are literal environment
            # perceptions: keep them raw so top-level comparator error reflects
            # the selected observation rather than an evolvable/smoothed mapping.
            self.activation_funcs["perception"][-1] = "linear"
        
        # Handle smooth factors — always stored as full dict. When the caller
        # does not provide them, initialize each active smooth unit randomly
        # rather than forcing every alpha to 0.5.
        if smooth_factors is None:
            action_shape = self.env_properties['action_shape']
            action_units = action_shape[0] if len(action_shape) > 0 else 1
            smooth_seed = (
                None
                if random_seed is None
                else np.random.SeedSequence([int(random_seed), 0x51A7])
            )
            smooth_rng = np.random.default_rng(smooth_seed)
            self.smooth_factors = self._random_smooth_factors(
                self.levels, self.activation_funcs, int(action_units), smooth_rng
            )
        else:
            self.smooth_factors = self._expand_smooth_factors(smooth_factors, self.activation_funcs, len(levels))
        
        # Handle weight types
        if isinstance(weight_types, str):
            self.weight_types = [weight_types] * len(levels)
        else:
            if len(weight_types) != len(levels):
                raise ValueError(f"weight_types length ({len(weight_types)}) must match levels length ({len(levels)})")
            self.weight_types = weight_types
        
        # Validate obs_connection_level
        if obs_connection_level >= len(levels):
            raise ValueError(f"obs_connection_level ({obs_connection_level}) must be < len(levels) ({len(levels)})")
        
        # Validate top_level_obs_indices and zerolevel_inputs_indexes
        if top_level_obs_indices is not None:
            if len(top_level_obs_indices) != levels[-1]:
                raise ValueError(
                    f"top_level_obs_indices length ({len(top_level_obs_indices)}) "
                    f"must equal top-level units ({levels[-1]})"
                )
            try:
                test_env = gym.make(env_name)
                obs_size = test_env.observation_space.shape[0] if hasattr(test_env.observation_space, 'shape') else test_env.observation_space.n
                test_env.close()
                for idx in top_level_obs_indices:
                    if idx < 0 or idx >= obs_size:
                        raise ValueError(
                            f"top_level_obs_indices contains invalid index {idx}: "
                            f"must be in [0, {obs_size - 1}] for observation space size {obs_size}"
                        )
            except ValueError:
                raise
            except Exception:
                pass
        
        if self.zerolevel_inputs_indexes is not None:
            if top_level_obs_indices is None:
                raise ValueError(
                    "zerolevel_inputs_indexes is only valid when "
                    "top_level_obs_indices is also provided"
                )
            try:
                test_env = gym.make(env_name)
                obs_size = test_env.observation_space.shape[0] if hasattr(test_env.observation_space, 'shape') else test_env.observation_space.n
                test_env.close()
                for idx in self.zerolevel_inputs_indexes:
                    if idx < 0 or idx >= obs_size:
                        raise ValueError(
                            f"zerolevel_inputs_indexes contains invalid index {idx}: "
                            f"must be in [0, {obs_size - 1}] for observation space size {obs_size}"
                        )
            except ValueError:
                raise
            except Exception:
                pass
        
        # Initialize state
        self.fixed_weights = fixed_weights.copy() if fixed_weights is not None else set()
        self.fixed_weights.add(f"RL{len(self.levels) - 1:02d}")
        if self.top_level_obs_indices is not None:
            self.fixed_weights.add(f"PL{len(self.levels) - 1:02d}")
        self.fixed_levels = fixed_levels if fixed_levels is not None else set()
        self.evolve_references = evolve_references
        self.model = None
        self.fitness = None
        self.fitness_method = None
        self.fitness_source = None
        self.fitness_observation_indices = None
        self.fitness_targets = None
        self.fitness_kwargs = {}
        self.weights = {}
        self.history = None
        self.run_steps = 0
        self.total_reward = 0.0
        self.last_reward = None
        self.success = None
        
        # Handle reference values
        top_level_units = self.levels[-1]
        if reference_values is not None:
            if len(reference_values) != top_level_units:
                raise ValueError(
                    f"reference_values length ({len(reference_values)}) must match "
                    f"top-level units ({top_level_units})"
                )
            self.reference_values = np.array(reference_values, dtype=np.float32)
        else:
            rng = np.random.default_rng(random_seed)
            self.reference_values = rng.uniform(-1.0, 1.0, top_level_units).astype(np.float32)



# %% ../nbs/00_individual.ipynb #e87a8222
def _repr_impl(self):
    """Implementation of __repr__ method."""
    compiled_status = "compiled" if self.model is not None else "uncompiled"
    if self.fitness is not None:
        if isinstance(self.fitness, (int, float, np.floating)):
            fitness_str = f", fitness={float(self.fitness):.2f}"
        elif hasattr(self.fitness, "values") and getattr(self.fitness, "valid", False):
            fitness_str = f", fitness={float(self.fitness.values[0]):.2f}"
        else:
            fitness_str = ""
    else:
        fitness_str = ""
    obs_level_str = f", obs_level={self.obs_connection_level}" if self.obs_connection_level != 0 else ""
    obs_indices_str = f", top_level_obs_indices={self.top_level_obs_indices}" if self.top_level_obs_indices is not None else ""
    zl_indices_str = f", zerolevel_inputs_indexes={self.zerolevel_inputs_indexes}" if self.zerolevel_inputs_indexes is not None else ""
    return f"DHPCTIndividual(env='{self.env_name}', levels={self.levels}, {compiled_status}{fitness_str}{obs_level_str}{obs_indices_str}{zl_indices_str})"

DHPCTIndividual.__repr__ = _repr_impl

# %% ../nbs/00_individual.ipynb #9770fc70
def _getstate_impl(self):
    """Pickle via portable DPCT config instead of serializing Keras model directly."""
    state = self.__dict__.copy()
    try:
        state["_pickle_config"] = self.config() if self.model is not None else None
    except Exception:
        state["_pickle_config"] = None
    state["model"] = None
    state["history"] = None
    return state


def _setstate_impl(self, state):
    """Restore a pickled individual, recompiling from config when available."""
    pickle_config = state.pop("_pickle_config", None)
    preserved_fitness = state.get("fitness", None)
    self.__dict__.update(state)
    if pickle_config is not None:
        restored = type(self).from_config(pickle_config)
        self.__dict__.update(restored.__dict__)
        self.fitness = preserved_fitness


DHPCTIndividual.__getstate__ = _getstate_impl
DHPCTIndividual.__setstate__ = _setstate_impl


# %% ../nbs/00_individual.ipynb #effbf4f5
_PERCEPTION_TERNARY_FLOAT_ELSE_WEIGHT_TYPES = {
    "ternary_perceptions_float_else",
    "ternary_perception_float_else",
    "perception_ternary_float_else",
}


def _effective_weight_type_impl(self, weight_type: str, role: str = "") -> str:
    """Resolve role-aware weight-type aliases to concrete initializer/mutation types.

    ``ternary_perceptions_float_else`` means perception connection weights use
    ternary values while reference/output/action connection weights remain
    continuous floats.  The shorter singular aliases are accepted for
    convenience/backward compatibility with early experiments.
    """
    if weight_type in _PERCEPTION_TERNARY_FLOAT_ELSE_WEIGHT_TYPES:
        return "ternary" if role == "perception" else "float"
    return weight_type


DHPCTIndividual._effective_weight_type = _effective_weight_type_impl


def _get_weight_initializer_impl(self, weight_type: str):
    """Get weight initializer for given concrete weight type."""
    if weight_type == "float":
        return keras.initializers.RandomUniform(minval=-1.0, maxval=1.0)
    elif weight_type == "boolean":
        return keras.initializers.Constant(value=1.0)  # Will be converted to boolean later
    elif weight_type == "ternary":
        return keras.initializers.Constant(value=0.0)  # Will be converted to ternary later
    elif weight_type in _PERCEPTION_TERNARY_FLOAT_ELSE_WEIGHT_TYPES:
        # Default to the non-perception side when no role is supplied. Role-aware
        # call sites use _effective_weight_type(..., role=...) before calling
        # this method.
        return keras.initializers.RandomUniform(minval=-1.0, maxval=1.0)
    else:
        raise ValueError(f"Unknown weight type: {weight_type}")

DHPCTIndividual._get_weight_initializer = _get_weight_initializer_impl


# %% ../nbs/00_individual.ipynb #ab173369
def _create_activated_dense_impl(
    self,
    input_tensor,
    units: int,
    activation: str,
    smooth_factor: float,
    name: str,
    weight_type_idx: int,
    weight_role: str = "perception",
):
    """Create a Dense layer with optional activation layer attachment."""
    # Get initializer based on role-aware weight type
    initializer = self._get_weight_initializer(
        self._effective_weight_type(self.weight_types[weight_type_idx], weight_role)
    )
    
    if activation == "smooth":
        # Create linear Dense layer
        dense = layers.Dense(
            units=units,
            activation="linear",
            name=name,
            kernel_initializer=initializer,
            use_bias=False,
        )(input_tensor)
        # Add ExponentialSmoothLayer
        smooth_layer = ExponentialSmoothLayer(
            smooth_factor=smooth_factor,
            name=f"{name}_smooth"
        )(dense)
        return smooth_layer
    elif activation == "sigmoid":
        # Create linear Dense layer
        dense = layers.Dense(
            units=units,
            activation="linear",
            name=name,
            kernel_initializer=initializer,
            use_bias=False,
        )(input_tensor)
        # Add SigmoidLayer
        sigmoid_layer = SigmoidLayer(name=f"{name}_sigmoid")(dense)
        return sigmoid_layer
    else:
        # Standard Keras activation
        return layers.Dense(
            units=units,
            activation=activation,
            name=name,
            kernel_initializer=initializer,
            use_bias=False,
        )(input_tensor)

DHPCTIndividual._create_activated_dense = _create_activated_dense_impl


# %% ../nbs/00_individual.ipynb #3eb68877
def _get_optimizer_instance_impl(self, optimizer_name: str, learning_rate: float):
    """Create optimizer instance for training.
    
    Args:
        optimizer_name: Name of optimizer ('adam', 'sgd', 'rmsprop', etc.)
        learning_rate: Learning rate for optimizer
        
    Returns:
        Keras optimizer instance
        
    Raises:
        ValueError: If optimizer name is not supported
    """
    optimizer_name = optimizer_name.lower()
    
    if optimizer_name == 'adam':
        return keras.optimizers.Adam(learning_rate=learning_rate)
    elif optimizer_name == 'sgd':
        return keras.optimizers.SGD(learning_rate=learning_rate)
    elif optimizer_name == 'rmsprop':
        return keras.optimizers.RMSprop(learning_rate=learning_rate)
    elif optimizer_name == 'adagrad':
        return keras.optimizers.Adagrad(learning_rate=learning_rate)
    else:
        raise ValueError(f"Unsupported optimizer: {optimizer_name}. Supported: adam, sgd, rmsprop, adagrad")

DHPCTIndividual._get_optimizer_instance = _get_optimizer_instance_impl

# %% ../nbs/00_individual.ipynb #15d864c6
def _compile_impl(self):
    """
    Build Keras Functional API model from hierarchy specification.
    
    Creates perception, reference, comparator, and output layers for each level
    following PCT principles. Initializes weights according to weight_types.
    
    If already compiled, allows recompilation by clearing the existing model.
    
    Raises:
        ValueError: If hierarchy specification is invalid
    """
    if self.model is not None:
        keras.backend.clear_session()
        self.model = None  # Allow recompilation
    num_levels = len(self.levels)
    
    # Set random seed for reproducibility
    if self.random_seed is not None:
        set_random_seed(self.random_seed)
    
    # Get environment dimensions
    obs_shape = self.env_properties['observation_shape']
    action_shape = self.env_properties['action_shape']
    obs_dim = obs_shape[0] if len(obs_shape) > 0 else 1
    action_dim = action_shape[0] if len(action_shape) > 0 else 1
    
    # Create input layers
    observations = layers.Input(shape=(obs_dim,), name='Observations')
    
    # Reference input dimension matches top-level unit count
    ref_dim = self.levels[-1]
    references_input = layers.Input(shape=(ref_dim,), name='ReferencesInput')
    
    # Storage for layer outputs
    perception_outputs = []
    reference_outputs = [None] * num_levels
    comparator_outputs = [None] * num_levels
    output_layer_outputs = [None] * num_levels
    
    def _effective_level0_observation_indices() -> Optional[List[int]]:
        """Return observation indices connected to level-0 perceptions.

        When the top level is wired directly to observations, those observation
        dimensions are removed from the bottom-level input so the same raw
        observation is not controlled independently at both hierarchy ends.
        """
        if num_levels == 1:
            return None

        if self.zerolevel_inputs_indexes is not None:
            candidate_indices = list(self.zerolevel_inputs_indexes)
        elif self.top_level_obs_indices is not None:
            candidate_indices = list(range(obs_dim))
        else:
            return None

        if self.top_level_obs_indices is not None:
            top_indices = set(int(idx) for idx in self.top_level_obs_indices)
            candidate_indices = [idx for idx in candidate_indices if int(idx) not in top_indices]

        if not candidate_indices:
            raise ValueError(
                "Level-0 observation inputs are empty after excluding "
                "top_level_obs_indices from the bottom-level perception input"
            )
        return candidate_indices

    level0_observation_indices = _effective_level0_observation_indices()
    self.level0_observation_indices = level0_observation_indices

    # === PASS 1: Build perception layers ===
    for level_idx, num_units in enumerate(self.levels):
        level_name = f"{level_idx:02d}"
        
        if level_idx == 0:
            # Level 0 connects to observations
            if self.top_level_obs_indices is not None and level_idx == num_levels - 1:
                # T024a: Single-level with direct observation connections
                gathered_obs = layers.Lambda(
                    lambda x: tf.gather(x, self.top_level_obs_indices, axis=1),
                    name=f"GatherObs{level_name}"
                )(observations)
                perception_layer = layers.Dense(
                    units=num_units,
                    activation="linear",
                    name=f"PL{level_name}",
                    kernel_initializer=keras.initializers.Identity(gain=1.0),
                    use_bias=False,
                    trainable=False,
                )(gathered_obs)
            elif level0_observation_indices is not None:
                # T024b / top-level direct observation: gather the effective
                # level-0 observation subset.  If top_level_obs_indices is set,
                # those dimensions are intentionally excluded from this bottom
                # input so they are controlled only by the direct top-level path.
                gathered_obs = layers.Lambda(
                    lambda x, idx=level0_observation_indices: tf.gather(x, idx, axis=1),
                    name=f"GatherObsL{level_name}"
                )(observations)
                perception_layer = self._create_activated_dense(
                    input_tensor=gathered_obs,
                    units=num_units,
                    activation=self.activation_funcs["perception"][level_idx],
                    smooth_factor=self.smooth_factors["perception"][level_idx],
                    name=f"PL{level_name}",
                    weight_type_idx=level_idx,
                    weight_role="perception"
                )
            else:
                # Standard observation connection
                perception_layer = self._create_activated_dense(
                    input_tensor=observations,
                    units=num_units,
                    activation=self.activation_funcs["perception"][level_idx],
                    smooth_factor=self.smooth_factors["perception"][level_idx],
                    name=f"PL{level_name}",
                    weight_type_idx=level_idx,
                    weight_role="perception"
                )
        elif level_idx == num_levels - 1 and self.top_level_obs_indices is not None:
            # T024a: Top level with direct observation connections
            gathered_obs = layers.Lambda(
                lambda x: tf.gather(x, self.top_level_obs_indices, axis=1),
                name=f"GatherObs{level_name}"
            )(observations)
            # Fixed one-to-one raw observation mapping. Do not allow this
            # path to evolve, add bias, or smooth/nonlinearly transform values;
            # otherwise top_level_comparator_error can be minimized by changing
            # the perception calibration instead of moving the environment state.
            perception_layer = layers.Dense(
                units=num_units,
                activation="linear",
                name=f"PL{level_name}",
                kernel_initializer=keras.initializers.Identity(gain=1.0),
                use_bias=False,
                trainable=False,
            )(gathered_obs)
        else:
            # Higher levels connect to lower level perception outputs
            prev_perception = perception_outputs[level_idx - 1]
            perception_layer = self._create_activated_dense(
                input_tensor=prev_perception,
                units=num_units,
                activation=self.activation_funcs["perception"][level_idx],
                smooth_factor=self.smooth_factors["perception"][level_idx],
                name=f"PL{level_name}",
                weight_type_idx=level_idx
            )
        
        perception_outputs.append(perception_layer)
    
    # === PASS 2: Build reference, comparator, and output layers ===
    for level_idx in reversed(range(num_levels)):
        level_name = f"{level_idx:02d}"
        num_units = self.levels[level_idx]
        
        # Reference layers
        if level_idx == num_levels - 1:
            # Top level connects to reference input with fixed unit gains. These
            # weights are intentionally not controlled by weight_type: top-level
            # reference values are external set-points and must pass through as-is.
            ref_initializer = keras.initializers.Ones()
            
            reference_layer = ElementWiseMultiplyLayer(
                units=num_units,
                weight_initializer=ref_initializer,
                name=f"RL{level_name}"
            )(references_input)
        else:
            # Lower levels connect to higher level outputs
            higher_output = output_layer_outputs[level_idx + 1]
            reference_layer = self._create_activated_dense(
                input_tensor=higher_output,
                units=num_units,
                activation=self.activation_funcs["reference"][level_idx],
                smooth_factor=self.smooth_factors["reference"][level_idx],
                name=f"RL{level_name}",
                weight_type_idx=level_idx,
                weight_role="reference"
            )
        
        reference_outputs[level_idx] = reference_layer
        
        # Comparator layers (error = reference - perception)
        comparator_layer = layers.Subtract(name=f"CL{level_name}")(
            [reference_outputs[level_idx], perception_outputs[level_idx]]
        )
        comparator_outputs[level_idx] = comparator_layer
        
        # Output layers (proportional control)
        output_layer = ElementWiseMultiplyLayer(
            units=num_units,
            weight_initializer=self._get_weight_initializer(
                self._effective_weight_type(self.weight_types[level_idx], "output")
            ),
            name=f"OL{level_name}"
        )(comparator_layer)
        
        # Apply activation if needed
        if self.activation_funcs["output"][level_idx] == "smooth":
            output_layer = ExponentialSmoothLayer(
                smooth_factor=self.smooth_factors["output"][level_idx],
                name=f"OL{level_name}_smooth"
            )(output_layer)
        elif self.activation_funcs["output"][level_idx] == "sigmoid":
            output_layer = SigmoidLayer(name=f"OL{level_name}_sigmoid")(output_layer)
        elif self.activation_funcs["output"][level_idx] != "linear":
            output_layer = layers.Activation(
                self.activation_funcs["output"][level_idx],
                name=f"OL{level_name}_activation"
            )(output_layer)
        
        output_layer_outputs[level_idx] = output_layer
    
    # Create action output from level 0 output
    actions = self._create_activated_dense(
        input_tensor=output_layer_outputs[0],
        units=action_dim,
        activation=self.activation_funcs["actions"],
        smooth_factor=self.smooth_factors["actions"],
        name="Actions",
        weight_type_idx=0,
        weight_role="actions"
    )
    
    # Create error output (concatenate all comparator outputs)
    if len(comparator_outputs) == 1:
        errors = layers.Lambda(lambda x: x, name="Errors")(comparator_outputs[0])
    else:
        errors = layers.Concatenate(name="Errors")(comparator_outputs)
    
    # Create the model
    self.model = keras.Model(
        inputs=[observations, references_input],
        outputs=[actions, errors],
        name="DHPCTIndividual"
    )
    
    # Store weights for easy access
    self._store_weights()

DHPCTIndividual.compile = _compile_impl


# %% ../nbs/00_individual.ipynb #1e140989
def _store_weights_impl(self):
    """Store current model weights in self.weights dictionary."""
    if self.model is None:
        return
    
    self.weights = {}
    for layer in self.model.layers:
        if hasattr(layer, 'get_weights') and len(layer.get_weights()) > 0:
            weights = layer.get_weights()
            if len(weights) > 0:
                self.weights[layer.name] = weights[0].copy()
            if len(weights) > 1:  # Bias weights
                self.weights[f"{layer.name}_bias"] = weights[1].copy()

DHPCTIndividual._store_weights = _store_weights_impl

# %% ../nbs/00_individual.ipynb #fa48214b
def _reset_smooth_layers_impl(self):
    """Reset state in all ExponentialSmoothLayer instances."""
    if self.model is None:
        return
    
    for layer in self.model.layers:
        if isinstance(layer, ExponentialSmoothLayer):
            layer.reset_state()

DHPCTIndividual._reset_smooth_layers = _reset_smooth_layers_impl

# %% ../nbs/00_individual.ipynb #262dbe0d
def _map_action(raw_action: np.ndarray, action_space) -> "Union[int, np.ndarray]":
    """Map raw model output to a valid environment action.

    Args:
        raw_action: Raw action array from the model's Actions output
            (1-D, already stripped of the batch dimension).
        action_space: The Gymnasium action space of the target
            environment (``env.action_space``).

    Returns:
        An ``int`` for discrete spaces or a clipped ``np.ndarray`` for
        continuous spaces.
    """
    if hasattr(action_space, 'n'):  # Discrete action space
        raw_values = np.asarray(raw_action).reshape(-1)
        if raw_values.size == 1:
            # Scalar discrete policies preserve PCT's signed control signal.
            # Binary spaces use sign: <= 0 -> 0, > 0 -> 1.
            # Ternary directional spaces such as MountainCar-v0/Acrobot-v1
            # use sign with zero as neutral: < 0 -> 0, == 0 -> 1, > 0 -> 2.
            scalar_action = float(raw_values[0])
            if getattr(action_space, 'n', None) == 3:
                if scalar_action < 0.0:
                    return 0
                if scalar_action > 0.0:
                    return 2
                return 1
            return int(scalar_action > 0.0)
        else:
            # Multi-output discrete policies select the highest-scoring action.
            return int(np.argmax(raw_values))
    else:  # Continuous action space
        # Clip action to valid range
        return np.clip(raw_action, action_space.low, action_space.high)

DHPCTIndividual.map_action = staticmethod(_map_action)

# %% ../nbs/00_individual.ipynb #630edc47
def _resolve_fitness_error_values(
    *,
    fitness_source: str,
    errors_list: List[np.ndarray],
    observation_values_list: List[np.ndarray],
    fitness_observation_indices: Optional[List[int]],
    fitness_targets: Optional[List[float]],
    pad_to_steps: Optional[int] = None,
    terminal_observation_values: Optional[np.ndarray] = None,
    top_level_units: Optional[int] = None,
) -> np.ndarray:
    """Return flattened errors from comparator outputs or observation deltas.

    When ``pad_to_steps`` is provided and the rollout ended before that
    horizon, the returned error array is padded to a fixed number of time
    steps.  This keeps RMS/MAE fitness comparable between early-terminated
    and full-horizon rollouts.  Observation-source fitness pads with the
    terminal observation when available (e.g. MountainCarContinuous reaching
    the goal); comparator-error fitness pads with the last observed comparator
    error because no comparator output exists for the post-step terminal
    observation.
    """
    requested_steps = int(pad_to_steps) if pad_to_steps is not None else None
    if requested_steps is not None and requested_steps < 0:
        raise ValueError(f"pad_to_steps must be >= 0, got {requested_steps}")

    if fitness_source in {"comparator_error", "top_level_comparator_error"}:
        error_rows = np.asarray(errors_list, dtype=np.float32)
        if error_rows.size == 0:
            return np.array([], dtype=np.float32)
        if error_rows.ndim == 1:
            error_rows = error_rows.reshape(-1, 1)
        if fitness_source == "top_level_comparator_error":
            if top_level_units is None:
                raise ValueError("top_level_units is required for fitness_source='top_level_comparator_error'")
            top_level_units = int(top_level_units)
            if top_level_units <= 0:
                raise ValueError(f"top_level_units must be > 0, got {top_level_units}")
            if top_level_units > error_rows.shape[1]:
                raise ValueError(
                    f"top_level_units ({top_level_units}) cannot exceed comparator error width "
                    f"({error_rows.shape[1]})"
                )
            error_rows = error_rows[:, -top_level_units:]
        if requested_steps is not None and error_rows.shape[0] < requested_steps:
            pad_count = requested_steps - error_rows.shape[0]
            pad_rows = np.repeat(error_rows[-1:, :], pad_count, axis=0)
            error_rows = np.vstack([error_rows, pad_rows])
        return error_rows.reshape(-1)

    all_observations = np.asarray(observation_values_list, dtype=np.float32)
    if all_observations.ndim == 1:
        all_observations = all_observations.reshape(-1, 1)

    if all_observations.size == 0:
        selected_observations = np.empty((0, 0), dtype=np.float32)
    elif fitness_observation_indices is None:
        selected_observations = all_observations
    else:
        obs_dim = all_observations.shape[1]
        invalid_indices = [idx for idx in fitness_observation_indices if idx < 0 or idx >= obs_dim]
        if invalid_indices:
            raise ValueError(
                f"fitness_observation_indices must be within [0, {obs_dim - 1}], "
                f"got {invalid_indices}"
            )
        selected_observations = all_observations[:, fitness_observation_indices]

    if selected_observations.ndim == 1:
        selected_observations = selected_observations.reshape(-1, 1)

    feature_count = selected_observations.shape[1]
    if fitness_targets is None:
        targets = np.zeros(feature_count, dtype=np.float32)
    else:
        if len(fitness_targets) != feature_count:
            raise ValueError(
                f"fitness_targets length ({len(fitness_targets)}) must match selected "
                f"observation count ({feature_count})"
            )
        targets = np.asarray(fitness_targets, dtype=np.float32)

    error_rows = selected_observations - targets
    if requested_steps is not None and error_rows.shape[0] < requested_steps:
        pad_count = requested_steps - error_rows.shape[0]
        if terminal_observation_values is not None:
            terminal_observation = np.asarray(terminal_observation_values, dtype=np.float32).reshape(1, -1)
            if fitness_observation_indices is None:
                selected_terminal = terminal_observation
            else:
                obs_dim = terminal_observation.shape[1]
                invalid_indices = [idx for idx in fitness_observation_indices if idx < 0 or idx >= obs_dim]
                if invalid_indices:
                    raise ValueError(
                        f"fitness_observation_indices must be within [0, {obs_dim - 1}], "
                        f"got {invalid_indices}"
                    )
                selected_terminal = terminal_observation[:, fitness_observation_indices]
            pad_error = selected_terminal - targets
        elif error_rows.shape[0] > 0:
            pad_error = error_rows[-1:, :]
        else:
            pad_error = np.zeros((1, feature_count), dtype=np.float32)
        pad_rows = np.repeat(pad_error, pad_count, axis=0)
        error_rows = np.vstack([error_rows, pad_rows])

    return error_rows.reshape(-1)


def _apply_failure_penalty(
    base_error: float,
    *,
    steps_completed: int,
    requested_steps: int,
    failure_penalty: float,
) -> float:
    """Return base error plus an incomplete-rollout penalty."""
    if requested_steps <= 0:
        raise ValueError(f"requested_steps must be > 0, got {requested_steps}")

    clamped_steps_completed = max(0, min(int(steps_completed), int(requested_steps)))
    completion_ratio = clamped_steps_completed / float(requested_steps)
    return float(base_error) + float(failure_penalty) * (1.0 - completion_ratio)


_BUILT_IN_FITNESS_METHODS = {
    "cumulative_reward",
    "evaluation_steps",
    "rms",
    "mae",
    "rms_adjusted",
    "adjusted_rms",
    "mae_adjusted",
    "adjusted_mae",
}


def _available_environment_fitness_methods(env_name: str) -> List[str]:
    """Return registered dpct-env fitness method names for an environment."""
    try:
        from dpct_env.fitness import get_fitness_functions
    except ImportError:
        return []
    try:
        return sorted(get_fitness_functions(env_name).keys())
    except Exception:
        return []


def _resolve_environment_fitness_function(fitness_method: str, env_name: str, fitness_kwargs: Optional[dict] = None):
    """Resolve an environment-specific fitness function via dpct-env.

    dpct-env owns the registry and all environment-specific scoring logic.
    This adapter keeps core dpct generic while tolerating both the current
    ``create_fitness_function(name, env_name)`` API and a future configurable
    ``create_fitness_function(name, env_name, **kwargs)`` API.
    """
    fitness_kwargs = dict(fitness_kwargs or {})
    try:
        from dpct_env.fitness import create_fitness_function, get_fitness_functions
    except ImportError as exc:
        raise ValueError(
            f"Unknown fitness_method '{fitness_method}'. Built-in methods: {sorted(_BUILT_IN_FITNESS_METHODS)}. "
            "Environment-specific fitness methods require the 'dpct-env' package."
        ) from exc

    try:
        try:
            return create_fitness_function(fitness_method, env_name=env_name, **fitness_kwargs)
        except TypeError as exc:
            if not fitness_kwargs:
                raise
            try:
                fitness_fn = create_fitness_function(fitness_method, env_name=env_name)
                return fitness_fn.__class__(**fitness_kwargs)
            except Exception:
                raise exc
    except KeyError as exc:
        available = sorted(get_fitness_functions(env_name).keys())
        raise ValueError(
            f"Unknown fitness_method '{fitness_method}' for env_name='{env_name}'. "
            f"Built-in methods: {sorted(_BUILT_IN_FITNESS_METHODS)}. "
            f"Registered environment-specific methods: {available}."
        ) from exc


def _run(
    self,
    steps: int = 500,
    early_termination: bool = False,
    render: bool = False,
    render_mode: Optional[str] = None,
    frame_callback: Optional[Callable[[np.ndarray], None]] = None,
    verbose: bool = False,
    train: bool = False,
    learning_rate: float = 0.01,
    optimizer='adam',
    train_every_n_steps: int = 10,
    error_weight_coefficients: Optional[List[float]] = None,
    fitness_method: Optional[str] = None,
    fitness_source: Optional[str] = None,
    fitness_observation_indices: Optional[List[int]] = None,
    fitness_targets: Optional[List[float]] = None,
    fitness_kwargs: Optional[dict] = None,
    record_history: bool = False,
    failure_penalty: float = 1.0,
):
    """Run individual in environment for specified number of steps.

    Args:
        steps: Maximum number of steps to run
        early_termination: Stop when environment terminates if True
        render: Render environment during execution
        render_mode: Optional Gymnasium render mode override (e.g. 'rgb_array')
        frame_callback: Optional callback receiving each rendered frame
        verbose: Print step-by-step information
        train: Enable online learning during execution
        learning_rate: Learning rate for online training
        optimizer: Optimizer name or optimizer instance for online training
        train_every_n_steps: Perform training update every N steps
        error_weight_coefficients: Optional per-level coefficients for error weighting (reserved)
        fitness_method: Method for fitness calculation ('cumulative_reward', 'evaluation_steps',
            'rms', 'mae', 'rms_adjusted'/'adjusted_rms', 'mae_adjusted'/'adjusted_mae').
            If None, reuse ``self.fitness_method`` from saved/evaluated metadata or
            fall back to ``'cumulative_reward'``.
        fitness_source: Source used by error fitness methods ('comparator_error',
            'top_level_comparator_error', or 'observation'). If None, reuse
            ``self.fitness_source`` or fall back to ``'comparator_error'``.
        fitness_observation_indices: Optional subset of observation indices used when fitness_source='observation'.
            If None, reuse ``self.fitness_observation_indices`` when present.
        fitness_targets: Optional per-index targets used when fitness_source='observation' (defaults to zeros).
            If None, reuse ``self.fitness_targets`` when present.
        fitness_kwargs: Optional configuration forwarded to environment-specific fitness factories
        record_history: Record detailed execution history for visualization
        failure_penalty: Penalty scale for adjusted error methods when rollout is incomplete

    Returns:
        Fitness score (higher is better for cumulative_reward/evaluation_steps, lower error is better for error methods)
    """
    if self.model is None:
        raise RuntimeError("Individual must be compiled before running")

    # ``fitness_*`` arguments are per-run overrides.  When omitted, prefer
    # metadata restored from ``from_config()`` (or from a prior evaluation) so
    # ``DHPCTIndividual.from_config(cfg).run()`` replays the saved objective.
    # Fall back to the historical defaults for fresh individuals.
    if fitness_method is None:
        fitness_method = self.fitness_method or "cumulative_reward"
    if fitness_source is None:
        fitness_source = self.fitness_source or "comparator_error"
    if fitness_observation_indices is None:
        fitness_observation_indices = self.fitness_observation_indices
    if fitness_targets is None:
        fitness_targets = self.fitness_targets
    
    if error_weight_coefficients is not None:
        num_levels = len(self.levels)
        if len(error_weight_coefficients) != num_levels:
            raise ValueError(
                f"error_weight_coefficients length ({len(error_weight_coefficients)}) "
                f"must match number of levels ({num_levels})"
            )

    if fitness_source not in {"comparator_error", "top_level_comparator_error", "observation"}:
        raise ValueError(
            "fitness_source must be 'comparator_error', 'top_level_comparator_error', "
            f"or 'observation', got '{fitness_source}'"
        )
    
    adjusted_error_methods = {"rms_adjusted", "adjusted_rms", "mae_adjusted", "adjusted_mae"}
    if fitness_method in adjusted_error_methods and steps <= 0:
        raise ValueError(f"requested_steps must be > 0, got {steps}")

    # Create environment
    import gymnasium as gym
    effective_render_mode = render_mode if render_mode is not None else ("human" if render else None)
    env = gym.make(self.env_name, render_mode=effective_render_mode)
    capture_frames = effective_render_mode == "rgb_array" or frame_callback is not None
    self.last_environment_history = None
    
    # Reset smooth layers at episode start
    self._reset_smooth_layers()
    
    # Initialize tracking variables
    total_reward = 0.0
    last_reward = None
    self.last_reward = None
    errors_list = []
    observation_values_list = []
    action_values_list = []
    info_list = []
    step_count = 0
    rollout_terminated = False
    terminal_observation_values = None
    
    # Setup online training if requested
    if train:
        import tensorflow as tf
        opt_instance = self._get_optimizer_instance(optimizer, learning_rate)
        self.model.compile(optimizer=opt_instance, loss='mse')
    
    # Always keep a lightweight execution history so environment-specific
    # processors can determine task success even when detailed layer history is
    # not requested.  Layer activations are captured only for record_history.
    from dpct_run.individual_utils import ExecutionHistory
    execution_history = ExecutionHistory()
    self.history = execution_history if record_history else None
    history_model = None
    activation_layer_names = []
    if record_history:
        # Build one combined model that returns actions/errors plus intermediate
        # layer activations in a single forward pass.  This is important for
        # stateful layers such as ExponentialSmoothLayer: calling self.model and
        # then a separate activation model would advance smooth-layer state twice
        # per environment step and change the controller's behaviour.
        intermediate_outputs = {}
        for layer in self.model.layers:
            if any(layer.name.startswith(prefix) for prefix in ('PL', 'RL', 'CL', 'OL')):
                intermediate_outputs[layer.name] = layer.output
        if intermediate_outputs:
            activation_layer_names = list(intermediate_outputs.keys())
            history_model = keras.Model(
                inputs=self.model.input,
                outputs=[self.model.output[0], self.model.output[1], *intermediate_outputs.values()]
            )
    
    try:
        # Reset environment. When random_seed is set we seed the environment for deterministic runs.
        reset_kwargs = {}
        if self.random_seed is not None:
            reset_kwargs['seed'] = int(self.random_seed)
        observation, info = env.reset(**reset_kwargs)
        observation = np.array(observation, dtype=np.float32).reshape(1, -1)

        if capture_frames:
            frame = env.render()
            if frame_callback is not None:
                frame_callback(frame)
        
        for step in range(steps):
            # Prepare reference input (zeros or configured values)
            ref_input = self.reference_values.reshape(1, -1)
            
            # Get model prediction, and optionally layer activations, with one
            # forward pass so history recording is observational only.
            activation_tensors = []
            if record_history and history_model is not None:
                model_outputs = history_model([observation, ref_input])
                action_pred, error_pred = model_outputs[0], model_outputs[1]
                activation_tensors = model_outputs[2:]
            else:
                action_pred, error_pred = self.model([observation, ref_input])
            
            action_values = action_pred.numpy()[0]
            error_values = error_pred.numpy()[0]
            observation_values = observation[0]
            
            # Map action to environment format
            raw_action = action_values  # Remove batch dimension
            env_action = self.map_action(raw_action, env.action_space)
            
            # Take step in environment
            next_observation, reward, terminated, truncated, info = env.step(env_action)
            done = terminated or truncated

            if capture_frames:
                frame = env.render()
                if frame_callback is not None:
                    frame_callback(frame)
            
            # Update tracking
            reward_value = float(reward)
            total_reward += reward_value
            last_reward = reward_value
            self.last_reward = reward_value
            errors_list.append(error_values)
            observation_values_list.append(observation_values)
            action_values_list.append(env_action)
            info_list.append(info)
            step_count += 1
            
            # Record lightweight execution history for task-success processors;
            # include layer activations only when detailed history is requested.
            layer_activations = None
            if record_history and activation_tensors:
                if not isinstance(activation_tensors, list):
                    activation_tensors = [activation_tensors]
                layer_activations = {
                    name: act.numpy()[0]
                    for name, act in zip(activation_layer_names, activation_tensors)
                }
            execution_history.add_step(
                observation=np.array(next_observation, dtype=np.float32),
                action=env_action,
                reward=reward,
                error=error_values,
                terminated=terminated,
                truncated=truncated,
                layer_activations=layer_activations,
                pre_observation=observation_values,
            )
            
            # Verbose output: show both sides of the transition.  The model's
            # perception/action are computed from current_obs; task success is
            # based on next_obs plus the environment termination flags.
            if verbose:
                print(f"Step {step}: current_obs={observation_values}")
                print(f"next_obs={np.array(next_observation, dtype=np.float32)}")
                print(f"error_pred={error_values}")
                print(f"action_pred={action_values}")
                print(f"reward={reward}, terminated={terminated}, truncated={truncated}, done={done}")
            
            # Training update
            if train and step % train_every_n_steps == 0:
                # Simple training: minimize prediction error
                target_error = np.zeros_like(error_pred.numpy())
                with tf.GradientTape() as tape:
                    _, pred_error = self.model([observation, ref_input])
                    loss = tf.reduce_mean(tf.square(pred_error - target_error))
                
                # Only compute gradients for weights involved in error computation (exclude Actions layer)
                trainable_weights_for_error = [
                    w for w in self.model.trainable_weights 
                    if not any(layer_name in w.name for layer_name in ['Actions'])
                ]
                gradients = tape.gradient(loss, trainable_weights_for_error)
                grad_var_pairs = [
                    (g, v) for g, v in zip(gradients, trainable_weights_for_error)
                    if g is not None
                ]
                if grad_var_pairs:
                    opt_instance.apply_gradients(grad_var_pairs)
            
            # Handle episode end without stepping a terminated environment.
            if done:
                terminal_observation_values = np.array(next_observation, dtype=np.float32)
                if early_termination:
                    if step_count < steps:
                        rollout_terminated = terminated
                    break
                observation, _ = env.reset(**reset_kwargs)
                observation = np.array(observation, dtype=np.float32).reshape(1, -1)
            else:
                observation = np.array(next_observation, dtype=np.float32).reshape(1, -1)
        
    except Exception as e:
        env.close()
        raise EnvironmentError(f"Error during environment execution: {e}")
    finally:
        self.last_environment_history = execution_history
        env.close()

    # Error-based fitness should be comparable across early-terminated and
    # full-horizon rollouts.  If execution stops early, pad the error trace to
    # the requested horizon instead of changing the RMS/MAE denominator.
    fixed_error_horizon = int(steps) if early_termination and step_count < int(steps) else None

    # Calculate fitness based on method
    if fitness_method == "cumulative_reward":
        fitness = total_reward
    elif fitness_method == "evaluation_steps":
        fitness = float(step_count)
    elif fitness_method in {"rms", "rms_adjusted", "adjusted_rms"}:
        from dpct_run.individual_utils import calculate_rms_error

        base_error = calculate_rms_error(_resolve_fitness_error_values(
            fitness_source=fitness_source,
            errors_list=errors_list,
            observation_values_list=observation_values_list,
            fitness_observation_indices=fitness_observation_indices,
            fitness_targets=fitness_targets,
            pad_to_steps=fixed_error_horizon,
            terminal_observation_values=terminal_observation_values,
            top_level_units=self.levels[-1],
        ))  # Positive, lower is better
        if fitness_method in {"rms_adjusted", "adjusted_rms"}:
            fitness = _apply_failure_penalty(
                base_error,
                steps_completed=step_count,
                requested_steps=int(steps),
                failure_penalty=failure_penalty,
            )
            fitness_method = "rms_adjusted"
        else:
            fitness = base_error
    elif fitness_method in {"mae", "mae_adjusted", "adjusted_mae"}:
        from dpct_run.individual_utils import calculate_mae_error

        base_error = calculate_mae_error(_resolve_fitness_error_values(
            fitness_source=fitness_source,
            errors_list=errors_list,
            observation_values_list=observation_values_list,
            fitness_observation_indices=fitness_observation_indices,
            fitness_targets=fitness_targets,
            pad_to_steps=fixed_error_horizon,
            terminal_observation_values=terminal_observation_values,
            top_level_units=self.levels[-1],
        ))  # Positive, lower is better
        if fitness_method in {"mae_adjusted", "adjusted_mae"}:
            fitness = _apply_failure_penalty(
                base_error,
                steps_completed=step_count,
                requested_steps=int(steps),
                failure_penalty=failure_penalty,
            )
            fitness_method = "mae_adjusted"
        else:
            fitness = base_error
    else:
        fitness_fn = _resolve_environment_fitness_function(
            fitness_method,
            env_name=self.env_name,
            fitness_kwargs=fitness_kwargs,
        )
        fitness = float(fitness_fn(
            observation_history=np.asarray(observation_values_list),
            action_history=np.asarray(action_values_list),
            info_history=info_list,
        ))
    
    # Update instance variables
    self.fitness = fitness
    self.fitness_method = fitness_method
    self.fitness_source = fitness_source
    self.fitness_observation_indices = fitness_observation_indices
    self.fitness_targets = fitness_targets
    self.fitness_kwargs = dict(fitness_kwargs or {})

    self.run_steps = step_count
    self.total_reward = float(total_reward)
    self.last_reward = last_reward

    # Generic success: completed the full horizon without early termination.
    generic_success = step_count >= steps and not rollout_terminated

    # Check for environment-specific task success override.
    # Some environments (e.g. MountainCarContinuous-v0) have a task success
    # condition that causes early termination (position >= 0.45 and velocity >= 0).
    # For these, the generic definition would incorrectly mark successful
    # episodes as failures. Ask dpct-env's processor factory for the selected
    # environment so core dpct does not hardcode environment-specific imports.
    task_success = None
    try:
        from dpct_env.processors import create_environment_results_processor
        processor = create_environment_results_processor(self.env_name)
        task_success = processor.get_task_success(
            individual=self,
            history=self.last_environment_history,
            env_name=self.env_name,
        )
    except (ImportError, AttributeError):
        pass  # dpct-env not installed or processor lacks override; use generic success only

    if task_success is not None:
        self.success = task_success
    else:
        self.success = generic_success

    # Store updated weights
    self._store_weights()

    return fitness

DHPCTIndividual.run = _run


# %% ../nbs/00_individual.ipynb #25c72754
def _evaluate(
    self,
    nevals: int = 1,
    aggregate: str = "mean",
    evaluation_seed: Optional[int] = None,
    **run_kwargs,
) -> float:
    """Evaluate fitness across multiple runs and aggregate the result.

    Args:
        nevals: Number of evaluations to run.
        aggregate: Aggregation method ('mean', 'max', 'min', 'median').
        evaluation_seed: Optional environment seed. When omitted, use the
            seed restored from saved metadata, falling back to the genome seed
            for older configs.
        **run_kwargs: Additional keyword arguments forwarded to ``run``.

    Returns:
        Aggregated fitness score.

    Raises:
        ValueError: If ``nevals`` or ``aggregate`` are invalid.
    """
    if nevals < 1:
        raise ValueError(f"nevals must be >= 1, got {nevals}")

    valid_aggregates = {"mean", "max", "min", "median"}
    if aggregate not in valid_aggregates:
        raise ValueError(
            f"aggregate must be one of {sorted(valid_aggregates)}, got '{aggregate}'"
        )

    if run_kwargs.get("fitness_method") == "adjusted_rms":
        run_kwargs = {**run_kwargs, "fitness_method": "rms_adjusted"}
    elif run_kwargs.get("fitness_method") == "adjusted_mae":
        run_kwargs = {**run_kwargs, "fitness_method": "mae_adjusted"}

    # Template-level wiring is set on the DHPCTIndividual at construction
    # time and baked into the compiled model. It must not flow through to
    # run(); strip it defensively so any caller passing these keys (e.g. an
    # optimizer run_params) doesn't trip ``_run() got an unexpected keyword
    # argument ...``.
    for _template_key in ("top_level_obs_indices", "reference_values"):
        run_kwargs.pop(_template_key, None)

    fitnesses: List[float] = []
    original_seed = self.random_seed
    if evaluation_seed is not None:
        self.evaluation_seed = int(evaluation_seed)
    saved_evaluation_seed = getattr(self, "evaluation_seed", None)
    base_evaluation_seed = (
        int(saved_evaluation_seed) if saved_evaluation_seed is not None else original_seed
    )

    try:
        for i in range(nevals):
            if base_evaluation_seed is not None:
                self.random_seed = int(base_evaluation_seed) + i
            fitnesses.append(float(self.run(**run_kwargs)))
    finally:
        # Initialization metadata belongs to the genome, not the rollout.
        self.random_seed = original_seed

    if aggregate == "mean":
        return float(np.mean(fitnesses))
    if aggregate == "max":
        return float(np.max(fitnesses))
    if aggregate == "min":
        return float(np.min(fitnesses))
    return float(np.median(fitnesses))

DHPCTIndividual.evaluate = _evaluate

# %% ../nbs/00_individual.ipynb #3291dfbe
from dpct_run.individual_utils import (
    calculate_rms_error,
    calculate_mae_error,
    _config_impl,
    _save_config_impl,
    _load_config_impl,
    _from_config_impl,
    _to_legacy_config_impl,
    config_to_legacy_config,
    _from_legacy_config_impl,
    _load_from_legacy_config_impl,
)

DHPCTIndividual.config = _config_impl
DHPCTIndividual.save_config = _save_config_impl
DHPCTIndividual.load_config = classmethod(_load_config_impl)
DHPCTIndividual.from_config = classmethod(_from_config_impl)
DHPCTIndividual.to_legacy_config = _to_legacy_config_impl
DHPCTIndividual.config_to_legacy_config = staticmethod(config_to_legacy_config)

DHPCTIndividual.from_legacy_config = classmethod(_from_legacy_config_impl)
DHPCTIndividual.load_from_legacy_config = classmethod(_load_from_legacy_config_impl)
