"""Shared Keras layers used across DPCT modules"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_layers.ipynb.

# %% auto #0
__all__ = ['ElementWiseMultiplyLayer', 'SigmoidLayer', 'ExponentialSmoothLayer']

# %% ../nbs/01_layers.ipynb #7092fd69
import os
os.environ.setdefault("TF_CPP_MIN_LOG_LEVEL", "2")
import numpy as np
import tensorflow as tf
from tensorflow.keras import layers

# %% ../nbs/01_layers.ipynb #08aed794
@tf.keras.utils.register_keras_serializable()
class ElementWiseMultiplyLayer(layers.Layer):
    """Custom layer for element-wise multiplication with learnable weights."""

    def __init__(self, units, weight_initializer, **kwargs):
        super().__init__(**kwargs)
        self.units = units
        self.weight_initializer = weight_initializer

    def build(self, input_shape):
        self.output_weights = self.add_weight(
            name='output_weights',
            shape=(self.units,),
            initializer=self.weight_initializer,
            trainable=True
        )
        super().build(input_shape)

    def call(self, inputs):
        return inputs * self.output_weights

    def get_config(self):
        config = super().get_config()
        config.update({
            'units': self.units,
            'weight_initializer': tf.keras.utils.serialize_keras_object(self.weight_initializer),
        })
        return config

    @classmethod
    def from_config(cls, config):
        config['weight_initializer'] = tf.keras.utils.deserialize_keras_object(
            config['weight_initializer']
        )
        return cls(**config)

# %% ../nbs/01_layers.ipynb #043c3abe
@tf.keras.utils.register_keras_serializable()
class SigmoidLayer(layers.Layer):
    """Scaled-sigmoid activation layer.

    Equivalent to the sigmoid applied by ``pct.functions.SigmoidWeightedSum``.
    Given input *x* (already the result of a weighted sum), computes::

        output = -R/2 + R / (1 + exp(-x * S / R))

    where *R* = ``range_val`` and *S* = ``slope``.

    Both parameters are stored as **trainable** weights so evolutionary
    operators can optimise them.

    Parameters
    ----------
    range_val : float or list of float, default 2.0
        Output is bounded to [-range_val/2, +range_val/2].
        When a list is provided, each element applies to the
        corresponding unit (per-unit parameterisation).
    slope : float or list of float, default 10.0
        Controls the steepness of the sigmoid curve.
        When a list is provided, each element applies to the
        corresponding unit.
    """

    def __init__(self, range_val=2.0, slope=10.0, **kwargs):
        super().__init__(**kwargs)
        if isinstance(range_val, (list, tuple)):
            self._init_range_val = [float(v) for v in range_val]
        else:
            self._init_range_val = float(range_val)
        if isinstance(slope, (list, tuple)):
            self._init_slope = [float(v) for v in slope]
        else:
            self._init_slope = float(slope)

    def build(self, input_shape):
        units = int(input_shape[-1])
        self.range_val = self.add_weight(
            name="range_val",
            shape=(units,),
            initializer=tf.constant_initializer(self._init_range_val),
            trainable=True,
        )
        self.slope = self.add_weight(
            name="slope",
            shape=(units,),
            initializer=tf.constant_initializer(self._init_slope),
            trainable=True,
        )
        super().build(input_shape)

    def call(self, inputs):
        r = self.range_val
        s = self.slope
        exponent = tf.clip_by_value(-inputs * s / r, -709.0, 709.0)
        return -r / 2.0 + r / (1.0 + tf.exp(exponent))

    def get_config(self):
        config = super().get_config()
        config.update({
            "range_val": self._init_range_val,
            "slope": self._init_slope,
        })
        return config

# %% ../nbs/01_layers.ipynb #c7bcb4ef
@tf.keras.utils.register_keras_serializable()
class ExponentialSmoothLayer(layers.Layer):
    """Stateful exponential-smoothing layer.

    Applies element-wise smoothing across successive calls:

        y_t = smooth_factor * y_{t-1} + (1 - smooth_factor) * x_t

    This matches the PCT library's ``smooth()`` function used inside
    ``pct.functions.SmoothWeightedSum``.

    Parameters
    ----------
    smooth_factor : float, default 0.5
        Initial smoothing coefficient.  0 = pass-through (no smoothing),
        1.0 = fully frozen (output never changes after first call).
        Stored as a **trainable** weight so evolutionary operators can modify it.
    """

    def __init__(self, smooth_factor: float = 0.5, **kwargs):
        super().__init__(**kwargs)
        self._init_smooth_factor = smooth_factor

    # -- build ----------------------------------------------------------
    def build(self, input_shape):
        units = input_shape[-1]

        init = np.array(self._init_smooth_factor, dtype=np.float32)
        if init.ndim == 0:
            # Keep one independent trainable smooth factor per output unit even
            # when callers provide a scalar shorthand. A scalar Keras variable
            # would be broadcast at runtime, forcing every unit in the layer to
            # share the same evolved alpha.
            init = np.full((units,), float(init), dtype=np.float32)
        elif init.shape != (units,):
            raise ValueError(
                f"smooth_factor vector shape {init.shape} must match input units {(units,)}"
            )
        smooth_shape = (units,)

        # Trainable: evolutionary operators can optimise this value
        self.smooth_factor = self.add_weight(
            name="smooth_factor",
            shape=smooth_shape,
            initializer=tf.constant_initializer(init),
            trainable=True,
        )

        # Non-trainable: runtime state, reset between episodes
        self.previous_output = self.add_weight(
            name="previous_output",
            shape=(units,),
            initializer="zeros",
            trainable=False,
        )

        super().build(input_shape)

    # -- call -----------------------------------------------------------
    def call(self, inputs):
        # Clamp smooth_factor to [0, 1] during forward pass
        sf = tf.clip_by_value(self.smooth_factor, 0.0, 1.0)
        new_output = sf * self.previous_output + (1.0 - sf) * inputs
        # Update state (works for every sample in the batch — uses last row)
        self.previous_output.assign(new_output[-1])
        return new_output

    # -- state reset ----------------------------------------------------
    def reset_state(self):
        """Reset previous_output to zeros.  Call at the start of each episode."""
        self.previous_output.assign(tf.zeros_like(self.previous_output))

    # -- serialisation --------------------------------------------------
    def get_config(self):
        config = super().get_config()
        init = np.array(self._init_smooth_factor)
        config.update({
            "smooth_factor": init.tolist() if init.ndim > 0 else float(init),
        })
        return config
